fix: COM-2547 320: Separator background image fix
CSSSR/csssr.blog pull request #232
Opened 2020-09-14 09:30 UTC by dyurein

## Задача
- ссылка на jira: https://jira.csssr.io/browse/COM-2547
- стенд: http://fix-com-2547.csssr-new-blog.csssr.cloud/

2020-09-15 08:36 UTC, ArtyomResh requested changes

2020-09-15 08:36 UTC, ArtyomResh commented on components/Post/Body/Separator/Separator.jsx
> +      <hr className={cn(className, type)} {...props} />
Давай тут будем не новый пропс `id` передавать, а добавлять как модификатор в `className` уже существующий `imageName`

2020-09-15 09:52 UTC, dyurein commented on components/Post/Body/Separator/Separator.jsx
> +      <hr className={cn(className, type)} {...props} />
![image](https://user-images.githubusercontent.com/37905737/93195564-0f0b5000-f752-11ea-80c1-466e763853e5.png)
![image](https://user-images.githubusercontent.com/37905737/93195673-2ea27880-f752-11ea-9b30-f9480a1b3650.png)
Задаю модификатор imageName классу, в итоге его почему то не видит

2020-09-15 09:52 UTC, dyurein commented on components/Post/Body/Separator/Separator.jsx
> +      <hr className={cn(className, type)} {...props} />
![image](https://user-images.githubusercontent.com/37905737/93195852-5d205380-f752-11ea-82a5-f06533481410.png)

2020-09-15 09:58 UTC, dyurein commented on components/Post/Body/Separator/Separator.jsx
> +      <hr className={cn(className, type)} {...props} />
Если передавать какой нибудь другой параметр, условный imageTitle, то с ним все нормально

2020-09-15 10:00 UTC, dyurein commented on components/Post/Body/Separator/Separator.jsx
> +      <hr className={cn(className, type)} {...props} />
![image](https://user-images.githubusercontent.com/37905737/93196661-6231d280-f753-11ea-869f-7c2a15fdff88.png)

2020-09-17 07:57 UTC, ArtyomResh reviewed
>Если передавать какой нибудь другой параметр, условный imageTitle, то с ним все нормально

2020-09-17 13:00 UTC, dyurein commented
> > Если передавать какой нибудь другой параметр, условный imageTitle, то с ним все нормально
> 
> Надо в Body.jsx, у компонента Separator этот пропс передать ему, он там скорей всего сразу в sources используется и не идёт дальше вниз

2020-09-28 12:04 UTC, dyurein commented
Забыл ревью заново запросить :/

2020-09-28 15:20 UTC, ArtyomResh approved these changes

2020-09-30 08:37 UTC, Yankovsky approved these changes

2020-09-30 08:37 UTC, Yankovsky commented on components/Post/Body/Separator/Separator.styles.js
> +    &&_peopleWithBasket {
А во что это превращается в css?

2020-10-02 12:25 UTC, dyurein commented on components/Post/Body/Separator/Separator.styles.js
> +    &&_peopleWithBasket {
`.родительский_класс.родительский_класс_peopleWithBascket`  - вроде в это

2020-10-02 12:26 UTC, dyurein commented on components/Post/Body/Separator/Separator.styles.js
> +    &&_peopleWithBasket {
@Yankovsky ^

2020-10-02 12:26 UTC, merged