COM-2527: Добавил возможность использовать исходное изображения без изменения размеров
CSSSR/csssr.blog pull request #263
Opened 2020-10-14 14:42 UTC by vkosinov

## Задача
- ссылка на jira: COM-2527
- стенд: http://fea-com-2527.csssr-new-blog.csssr.cloud/

## Чек-лист
- [x] PR в ветку релиза
- [x] Указаны ревьюеры
- [ ] Обновил документацию

2020-10-14 14:44 UTC, vkosinov commented on lib/api.js
> +      try {
Вот в этой конструкции не уверен, но отрабатывает как нужно

2020-10-16 08:31 UTC, ArtyomResh commented
430 файлов 😨

2020-10-16 08:35 UTC, vkosinov commented
> 430 файлов 😨

В основном это из за того что мы поменяли называния папок для изображений

2020-10-16 12:22 UTC, ArtyomResh requested changes
Я думаю, что надо ещё компонент Img отрефакторить из Body img убрать, насколько я понимаю мы все изображения в своих статьях будем сами хостить. Так же похоже надо csssr.images допилить, потому что гифки в статье «Кодекс тестировщика» поломались и больше не проигрываются

2020-10-16 12:22 UTC, ArtyomResh commented on lib/api.js
> +      try {
Выглядит, конечно, немного хаково :)
Давай заменим весь try ... catch на: 
```suggestion
items[field] = {
        ...(dataByLanguagePostAndImageResize?.[language]?.[slug] ?? {}),
        ...(dataByLanguagePostAndImageDontResize?.[language]?.[slug] ?? {}),
}
```

2020-10-21 15:53 UTC, vkosinov commented on _posts/ru/semantics-in-programming.md
> +![coupling-vs-cohesion](/images/dont-resize/ru/semantics-in-programming/coupling-vs-cohesion.svg)
svg и gif решили пока подключать через обычный img

2020-10-22 08:24 UTC, ArtyomResh commented on docs/ru/NEW_ARTICLE.md
> +
Красота <3

2020-10-22 08:24 UTC, ArtyomResh approved these changes

2020-10-22 09:27 UTC, merged