feat: COM-2849 Добавил страницу новостей
CSSSR/csssr.blog pull request #270
Opened 2020-10-15 11:37 UTC by vkosinov

## Задача
- ссылка на jira: COM-2849
- стенд: http://feat-com-2849.csssr-new-blog.csssr.cloud/

## Чек-лист
- [x] PR в ветку релиза
- [ ] Указаны ревьюеры
- [ ] Обновил документацию

2020-10-20 16:35 UTC, dyurein approved these changes

2020-10-21 08:49 UTC, ArtyomResh requested changes

2020-10-21 08:49 UTC, ArtyomResh commented on lib/api.js
> +    }
А как же `field === 'images'`? На страницах же будут изображение :)

2020-10-21 08:49 UTC, ArtyomResh commented on lib/api.js
> +        return getPostNewsBySlug(slug, 'ru', fields)
Второй аргумент можешь захордкодить внутри функции, у нас новости будут только на ру, а если появятся на англ, то отрефакторить функцию будет легко

2020-10-21 08:49 UTC, ArtyomResh commented on pages/_document.js
> +          />
Давай тут сразу на два разобьём, у нас Amita на ру теперь тоже будет использоваться

2020-10-21 08:49 UTC, ArtyomResh commented on components/main/Pagination/PrevPageLink/PrevPageLink.jsx
> +    href = `/${language}/${activeCategory.toLowerCase()}/${activePageNumber - 1}`
Я думаю тут as теперь можно совсем убрать

2020-10-21 08:49 UTC, ArtyomResh commented on components/main/Pagination/Pagination.jsx
> +          href = `/${language}/${activeCategory.toLowerCase()}/${pageNumber}`
Я думаю тут as теперь можно совсем убрать

2020-10-21 08:49 UTC, ArtyomResh commented on components/main/Pagination/NextPageLink/NextPageLink.jsx
>        as={`/${language}/${activeCategory.toLowerCase()}/${activePageNumber + 1}`}
Я думаю тут as теперь можно совсем убрать

2020-10-21 08:49 UTC, ArtyomResh commented on components/main/Categories/Categories.jsx
> +          )}
Напомни, пожалуйста, почему ты сказал будет лучше сделать категории отдельно не вставляя их в `categoriesOrder`?

2020-10-21 08:49 UTC, ArtyomResh commented on components/News/index.js
> +export { default } from './News'
Давай всё что касается старницы с новостями положим в папку с названием этой страницы, т.e. `components/news512/.....`

2020-10-21 08:49 UTC, ArtyomResh commented on components/News/News.jsx
> +        <meta property="og:url" content={`https://blog.csssr.com/${language}/news512/`} />
Думаю тут тоже можно вхардокить ру, про английскую версию ничего не известо

2020-10-21 08:49 UTC, ArtyomResh commented on components/News/News.jsx
> +            language={language}
И тут хардкод ру

2020-10-21 08:49 UTC, ArtyomResh commented on components/News/News.jsx
> +          language={language}
И тут хардкод ру

2020-10-21 08:49 UTC, ArtyomResh commented on components/News/News.jsx
> +            <DateFormatter language="ru">{lastPostDate}</DateFormatter>
А вот тут уже :)

2020-10-21 08:49 UTC, ArtyomResh commented on components/News/News.jsx
> +            <span className="tag">новости</span>
А тут не надо эмоджи огонька делать?

2020-10-21 08:49 UTC, ArtyomResh commented on components/News/NewsList/NewsList.jsx
> +    </div>
Сделай это списком ul > li

2020-10-21 08:49 UTC, ArtyomResh commented on components/News/NewsList/NewsList.jsx
> +          <Grid as="a" className={cn('news-item', { first: index === 0 })}>
Можно в css `first-of-type` или `nth-of-type(1)` :)

2020-10-21 08:49 UTC, ArtyomResh commented on pages/ru/news512/[page].js
> +  const pageNumber = Math.ceil(postsNews.length / POSTS_PER_PAGE)
А почему не стал использовать существующую функцию `calculatePageNumberByPostIndex`?

2020-10-21 08:49 UTC, ArtyomResh commented on pages/ru/news512/[page].js
> +  const pageNumber = Math.ceil(postsNews.length / POSTS_PER_PAGE)
Судя по макетам POSTS_PER_PAGE тут не подойдёт, потому что на странице может быть как-минимум 12 ссылок на статьи

2020-10-21 09:52 UTC, vkosinov commented on components/main/Categories/Categories.jsx
> +          )}
Если добавить в `categoriesOrder` то он будет искать категорию `news512` по пути `pages/[language]/[category]` подставлять туда компоненты для категорий.

2020-10-21 10:07 UTC, vkosinov commented on components/News/News.jsx
> +            <span className="tag">новости</span>
Нет на самой странице без него

2020-10-21 11:40 UTC, vkosinov commented on components/News/NewsList/NewsList.jsx
> +          <Grid as="a" className={cn('news-item', { first: index === 0 })}>
выделена должна быть только самая свежая статья, поменял логику

2020-10-21 11:48 UTC, vkosinov commented on pages/ru/news512/[page].js
> +  const pageNumber = Math.ceil(postsNews.length / POSTS_PER_PAGE)
Именно поэтому и не стал )

2020-10-22 07:42 UTC, ArtyomResh commented on components/main/Categories/Categories.jsx
> +          )}
Точно, спасибо!

2020-10-22 07:44 UTC, ArtyomResh commented on components/News/NewsList/NewsList.jsx
> +          <Grid as="a" className={cn('news-item', { first: index === 0 })}>
Да, но она же по-любому будет первая в списке или я что-то упустил? :D

2020-10-22 07:45 UTC, vkosinov commented on components/News/NewsList/NewsList.jsx
> +          <Grid as="a" className={cn('news-item', { first: index === 0 })}>
на каждой странице перый элемент свой

2020-10-22 07:49 UTC, ArtyomResh requested changes

2020-10-22 07:49 UTC, ArtyomResh commented on components/main/Pagination/Pagination.jsx
> +  isNews,
Давай тут пропс isNews заменим на пропс postsPerPage и будем из компонентов странице передавать в него POSTS_PER_PAGE и NEWS_PER_PAGE, так меньше исправлений надо будет делать в этом компоненте в будущем и его будет проще переиспользовать

2020-10-22 07:49 UTC, ArtyomResh commented on components/main/Pagination/Pagination.jsx
> +  isNews,
В дефолт можно POSTS_PER_PAGE поставить, что бы на главной не вносить изменения

2020-10-22 07:50 UTC, vkosinov commented on components/News/NewsList/NewsList.jsx
> +          <Grid as="a" className={cn('news-item', { first: index === 0 })}>
т.е. на второй странице первый элемент уже не будет самой крайней статьей

2020-10-22 07:50 UTC, ArtyomResh commented on components/News/NewsList/NewsList.jsx
> +          <Grid as="a" className={cn('news-item', { first: index === 0 })}>
Да, но для html и css селекторов он всегда первый же будет  :)

2020-10-22 07:54 UTC, vkosinov commented on components/News/NewsList/NewsList.jsx
> +          <Grid as="a" className={cn('news-item', { first: index === 0 })}>
а должен быть выделен только первый на первой странице,  возможно я что-то упустил )

2020-10-22 08:13 UTC, ArtyomResh commented on components/News/NewsList/NewsList.jsx
> +          <Grid as="a" className={cn('news-item', { first: index === 0 })}>
Ага, вот оно что, а я думал всегда первый выделяем. Тогда уточни, пожалуйста, у дизайнеров что им нужно

2020-10-22 08:15 UTC, vkosinov commented on components/News/NewsList/NewsList.jsx
> +          <Grid as="a" className={cn('news-item', { first: index === 0 })}>
>выделена должна быть только самая свежая статья, поменял логику

я уточнил и поправил логику )

2020-10-22 11:26 UTC, ArtyomResh approved these changes

2020-10-22 11:34 UTC, merged