[COM-2866]: Added news card
CSSSR/csssr.blog pull request #271
Opened 2020-10-19 08:18 UTC by BenuelBertran

## Задача
- ссылка на jira: COM-2866
- стенд: http://com-2866.csssr-new-blog.csssr.cloud/

## Чек-лист
- [ ] PR в ветку релиза
- [+] Указаны ревьюеры
- [ ] Обновил документацию

2020-10-23 11:10 UTC, ArtyomResh requested changes
Направь ветку в `release/NEWS-512`

2020-10-23 11:10 UTC, ArtyomResh commented on pages/[language]/index.js
> +  const allNews = await getPostsNews([
Думаю тут лучше просто `news`

2020-10-23 11:10 UTC, ArtyomResh commented on pages/[language]/[category]/[page].js
> +  const allNews = await getPostsNews([
Думаю тут лучше просто `news`

2020-10-23 11:10 UTC, ArtyomResh commented on pages/[language]/[category]/[page].js
>      },
Тут аналогично комменту в файле `pages/[language]/index.js`, только в методе `.map` для `news` в условие добавляется `(params.category === 'all')`, а вместо `allNews[allNews.length - 1]` нужно будет возвращать `allNews.reverse().slice(0, 3)[params.page - 1]`.

2020-10-26 09:59 UTC, dyurein commented on components/main/Posts/PostCard/PostCard.jsx
> +const PostCard = ({ className, language, post, size, isNews }) => {
Исправил

2020-10-26 11:24 UTC, dyurein commented on components/main/Posts/PostCard/PostCard.jsx
>        <Link href="/[language]/article/[slug]" as={`/${language}/article/${post.slug}`}>
Исправил

2020-10-26 12:33 UTC, dyurein commented on components/main/Posts/PostCard/PostCard.jsx
>        </Link>
Исправил

2020-10-26 14:34 UTC, dyurein commented on components/main/Posts/PostCard/PostCard.jsx
> +          onMouseOut={() => setIsLinkHovered(false)}
Добавил проверку в css

2020-10-27 08:07 UTC, dyurein commented on components/main/Posts/PostCard/PostCard.styles.js
> +      }
Поменял расположение цифры для реализации ховера, теперь отрабатывает нормально

2020-10-27 08:12 UTC, dyurein commented on data/categoriesByLanguage.js
> +  'news',
Убрал

2020-10-27 14:32 UTC, ArtyomResh requested changes

2020-10-27 14:32 UTC, ArtyomResh commented on components/main/Posts/PostCard/PostCard.jsx
> +      <Link href={type === 'news' ? '/ru/news512' : '/[language]/[category]'}>
Тут надо заменить

```suggestion
      <Link href={type === 'news' ? '/ru/news512' : `/${language}/${post.tag.toLowerCase()}`}>
```

2020-10-27 14:32 UTC, ArtyomResh commented on components/main/Posts/PostCard/PostCard.jsx
> +    episode: string,
Давай тут сделаем number и в файлах новостей строки поменяем на номер

2020-10-27 14:32 UTC, ArtyomResh commented on components/main/Posts/PostCard/PostCard.jsx
> +          {type === 'news' && <span className="news-number">#{post.episode}</span>}
[На карточках не показывается эпизод](http://s.csssr.ru/U31J879TR/20201027171000.jpg)

2020-10-27 14:32 UTC, ArtyomResh commented on components/main/Posts/PostCard/PostCard.jsx
>            />
Что-то случилось с изображением для новостей, оно теперь другое, в макете [приёмник](http://s.csssr.ru/U31J879TR/20201027171231.jpg), а на локальном сервере [диалоговые облачка](http://s.csssr.ru/U31J879TR/20201027171700.jpg)

2020-10-27 14:32 UTC, ArtyomResh commented on components/main/Posts/PostCard/PostCard.jsx
> +      <Link href={type === 'news' ? '/ru/news512' : '/[language]/[category]'}>
Иначе переход из пагинации на вторую страницу [ломается](http://s.csssr.ru/U31J879TR/20201027171753.jpg)

2020-10-27 14:32 UTC, ArtyomResh commented on postsOrderRuFullVersion.json
> +  ["work-better", "news-512-11"],
@dyurein тут забыл внести исправления

2020-10-27 14:32 UTC, ArtyomResh commented on pages/[language]/[category]/[page].js
> +import sortByDate from '../../../utils/sortByDate'
Подвинь этот импорт к импортам других выше утилит, пусть все импорты из utils будут рядом друг с другом

2020-10-27 14:32 UTC, ArtyomResh commented on pages/[language]/index.js
> +import sortByDate from '../../utils/sortByDate'
Подвинь этот импорт к импортам других выше утилит, пусть все импорты из utils будут рядом друг с другом

2020-10-27 14:32 UTC, ArtyomResh commented on pages/[language]/[category]/[page].js
> +  let postsWithNewsByLanguageAndCategoryAndPage = postsByLanguageAndCategoryAndPage
Тут можно не заводить эту переменную, оставь просто `postsByLanguageAndCategoryAndPage`, потому что у нас не всегда посты будут с новостями, например, на 4+ странице на ру их нет и на английском языке тоже

2020-10-27 14:32 UTC, ArtyomResh commented on pages/[language]/[category]/[page].js
> +      posts: postsWithNewsByLanguageAndCategoryAndPage.slice(0, POSTS_PER_PAGE),
Тут `.slice()` не нужен, мы уже в `postsByLanguageAndCategoryAndPage` отфильтровали статьи по номеру страницы

2020-10-27 14:32 UTC, ArtyomResh commented on components/main/Posts/PostCard/PostCard.jsx
> +      <Link href={type === 'news' ? '/ru/news512' : '/[language]/[category]'}>
Из-за этого, кстати, скорей всего сборка валится

2020-10-28 07:13 UTC, dyurein commented on postsOrderRuFullVersion.json
> +  ["work-better", "news-512-11"],
Точно, исправил

2020-10-28 07:22 UTC, dyurein commented on components/main/Posts/PostCard/PostCard.jsx
> +      <Link href={type === 'news' ? '/ru/news512' : '/[language]/[category]'}>
@ArtyomResh Заменил и у меня все равно падает ошибка :/

2020-10-28 07:23 UTC, dyurein commented on components/main/Posts/PostCard/PostCard.jsx
> +    episode: string,
Исправил

2020-10-28 07:36 UTC, dyurein commented on components/main/Posts/PostCard/PostCard.jsx
> +          {type === 'news' && <span className="news-number">#{post.episode}</span>}
Исправил

2020-10-28 07:59 UTC, dyurein commented on components/main/Posts/PostCard/PostCard.jsx
>            />
Исправил

2020-10-28 08:01 UTC, dyurein commented on pages/[language]/index.js
> +import sortByDate from '../../utils/sortByDate'
Исправил

2020-10-28 08:06 UTC, dyurein commented on pages/[language]/[category]/[page].js
> +  let postsWithNewsByLanguageAndCategoryAndPage = postsByLanguageAndCategoryAndPage
Убрал

2020-10-28 08:06 UTC, dyurein commented on pages/[language]/[category]/[page].js
> +      posts: postsWithNewsByLanguageAndCategoryAndPage.slice(0, POSTS_PER_PAGE),
Убрал

2020-10-28 08:25 UTC, dyurein commented on components/main/Posts/PostCard/PostCard.jsx
> +      <Link href={type === 'news' ? '/ru/news512' : '/[language]/[category]'}>
Понял, не у всех новостей стоял тег

2020-10-29 12:31 UTC, merged