feat: COM-2861 Add news page
CSSSR/csssr.blog pull request #276
Opened 2020-10-21 09:54 UTC by dyurein

## Задача
- ссылка на jira: https://jira.csssr.io/browse/COM-2861,
https://jira.csssr.io/browse/COM-2862,
https://jira.csssr.io/browse/COM-2863,
https://jira.csssr.io/browse/COM-2864
- стенд: http://feat-com-2861.csssr-new-blog.csssr.cloud/

2020-10-22 16:33 UTC, ArtyomResh requested changes
Ошибка при сборке: 
```
Error occurred prerendering page "/ru/news512/episode/[slug]". Read more: https://err.sh/next.js/prerender-error
TypeError: Cannot read property 'title' of undefined
```
В ревью описал решение этой проблемы

2020-10-22 16:33 UTC, ArtyomResh commented on _posts/news512/news-12.md
> +<Subtitle className="newsSubtitle">В этом выпуске: путь обучения фронтенду от Mozilla, комбинация флексов и гридов, тестовые задания компаний, материалы по Vue 3, протокол QUIC, релизы PHP-фреймворко
Давай менять не класс, а добавлять новые пропсы. Тут, например, `size='l'` и уже внутри будем по нему менять класс и по классу стили

2020-10-22 16:33 UTC, ArtyomResh commented on components/Post/Header/Header.jsx
> +        <Link href="/[language]/[category]" as={`/${language}/${tag}512`}>
В старых постах теперь сломалась эта ссылка

2020-10-22 16:33 UTC, ArtyomResh commented on components/Post/Header/Header.jsx
> +const Header = ({ className, title, author, tag, date, coverImage, alt, language, isNews }) => {
давай пропс `isNews` заменим на `type`, у которого будет два значения: `regular` и `news`, по дефолту `regular`

2020-10-22 16:33 UTC, ArtyomResh commented on components/Post/Header/Header.jsx
> +        newsHeader: isNews,
Вижу что это используется только один раз вот тут: 
```
    & {
      padding-top: 37px;
    }

    &.newsHeader {
      padding-top: 36px;
    }
```

Думаю можно не вводить новый класс и правило из-за одного пикселя, скорей всего это ошибка в дизайне :)

2020-10-22 16:33 UTC, ArtyomResh commented on components/Post/Header/Header.jsx
> +      />
Повесь один класс модификатор на родителя в зависимости от значение пропса type и по нему менять стили для этих компонентов. Можешь их собрать в одном стилевом блоке:
```
&.type_news {
    .title {...}
    
    .picture {...}
}
```

2020-10-22 16:33 UTC, ArtyomResh commented on components/Post/Header/Header.styles.js
> +    width: 120px;
Если правило общее для всех разрешений, то его размеры нужно записывать в ремах, а если нет, то класть его в медиа-блок определённого разрешения

2020-10-22 16:33 UTC, ArtyomResh commented on components/Post/Post.jsx
> +const Post = ({ post, language, className, isNews }) => {
Аналогично `<Header>`, давай пропс `isNews` заменим на `type`, у которого будет два значения: `regular` и `news`, по дефолту `regular`

2020-10-22 16:33 UTC, ArtyomResh commented on components/Post/Post.jsx
> +        newsPost: isNews,
тут пусть модификатор будет `type_news` если `type === 'news'`

2020-10-22 16:33 UTC, ArtyomResh commented on components/Post/Post.jsx
> +        number={post.number && post.number}
Можно просто post.number :)

2020-10-22 16:33 UTC, ArtyomResh commented on public/icons/newsLink/arrow_hover.svg
> +</svg>
А это тогда удалим

2020-10-22 16:33 UTC, ArtyomResh commented on components/news512/News/NewsList/NewsList.jsx
> +              <span className="news-item-title">{cleaningTitle(title)}</span>
👍

2020-10-22 16:33 UTC, ArtyomResh commented on data/categoriesByLanguage.js
> +  'news',
Это нужно отсюда убрать или же на страницах [categories] сделать исключение для категории `news`, поговори об этом с @vkosinov он сталкивался с этой проблемой и делал для неё решение.

Проблема заключается в том, что при клике на категорию новостей в списке новостей у тебя [появляется ошибка](http://s.csssr.ru/U31J879TR/20201022193117.jpg)

2020-10-22 16:33 UTC, ArtyomResh commented on pages/ru/news512/episode/[slug].js
> +  // }
Можешь удалить эти комменты

2020-10-22 16:33 UTC, ArtyomResh commented on pages/ru/news512/episode/[slug].js
> +      */}
И эти тоже

2020-10-23 06:24 UTC, vkosinov commented on data/categoriesByLanguage.js
> +  'news',
Нужно убрать,  ссылка на новости в категории подставляется в компоненте, в зависимости от локали

2020-10-23 07:39 UTC, dyurein commented on components/Post/Body/Body.jsx
> +              newsPostBody: isNews,
Понял, исправил

2020-10-23 07:41 UTC, dyurein commented on components/Post/Body/Body.styles.js
> -
Вернул

2020-10-23 07:54 UTC, dyurein commented on components/Post/Body/Img/Img.styles.js
> +    }
Убрал, не нужный стиль

2020-10-23 08:08 UTC, dyurein commented on components/Post/Body/NewsLink/NewsLink.styles.js
> +      }
@ArtyomResh Не очень понял зачем в `mobile.all` выносить. Тут ховер задается для десктопа, на таблете и мобильном уже другие изображения будет

2020-10-23 08:33 UTC, dyurein commented on components/Post/Body/NewsLink/NewsLink.jsx
> +  <div className={className}>
Убрал

2020-10-23 08:37 UTC, dyurein commented on components/Post/Body/NewsLink/NewsLink.styles.js
> +    color: #7D7FFE;
Исправил

2020-10-23 09:58 UTC, dyurein commented on components/Post/Body/ParagraphWithImage/ParagraphWithImage.styles.js
> +    width: ${calcRem(184)};
Исправил

2020-10-23 10:02 UTC, dyurein commented on components/Post/Body/ParagraphWithImage/ParagraphWithImage.styles.js
> +    min-height: auto;
Исправил

2020-10-23 10:53 UTC, dyurein commented on public/icons/newsLink/arrow.svg
> +</svg>
Переделал

2020-10-23 12:10 UTC, dyurein commented on components/Post/Header/Header.jsx
> +        <Link href="/[language]/[category]" as={`/${language}/${tag}512`}>
Исправил

2020-10-23 12:34 UTC, dyurein commented on components/Post/Header/Header.jsx
> +const Header = ({ className, title, author, tag, date, coverImage, alt, language, isNews }) => {
Поменял

2020-10-23 12:40 UTC, dyurein commented on components/Post/Header/Header.jsx
> +        newsHeader: isNews,
Убрал

2020-10-23 13:23 UTC, dyurein commented on components/Post/Header/Header.jsx
> +      />
Исправил

2020-10-23 13:24 UTC, dyurein commented on components/Post/Header/Header.styles.js
> +    width: 120px;
Исправил

2020-10-23 13:24 UTC, dyurein commented on components/Post/Post.jsx
> +const Post = ({ post, language, className, isNews }) => {
Переделал

2020-10-23 13:30 UTC, dyurein commented on components/Post/Post.jsx
> +        newsPost: isNews,
Исправил

2020-10-23 13:39 UTC, dyurein commented on data/categoriesByLanguage.js
> +  'news',
@ArtyomResh У меня падает как раз эта ошибка, когда я убираю `news` из `categoriesOrder`

2020-10-23 13:44 UTC, dyurein commented on components/Post/Body/NewsLink/NewsLink.styles.js
> +      }
А, догнал :)

2020-10-23 15:33 UTC, ArtyomResh requested changes

2020-10-23 15:33 UTC, ArtyomResh commented on components/Post/Body/ParagraphWithImage/ParagraphWithImage.jsx
> +        newsParagraphWithImage: imageSide === 'right',
Попробуй сначала сам что-то придумать, а если не получится, то гляди в следующий коммент в это треде :)

2020-10-23 15:33 UTC, ArtyomResh commented on components/Post/Body/ParagraphWithImage/ParagraphWithImage.jsx
> +          'img-wrap_right-side': imageSide === 'right',
Третий коммент в треде выше как раз одна из причин почему я предпочитаю не писать полностью по БЭМ, приходится вот такие конструкции выписывать ```[`${className}_with_right-side-image`]``` :)

2020-10-23 15:33 UTC, ArtyomResh commented on components/Post/Body/ParagraphWithImage/ParagraphWithImage.jsx
> +        newsParagraphWithImage: imageSide === 'right',
Если изменений слишком много и сложно их вывести в одну абстракцию, то можно буквально отразить изменения блока: 
```
[`${className}_with_right-side-image`]: imageSide === 'right',
```

2020-10-23 15:33 UTC, ArtyomResh commented on components/Post/Body/Subtitle/Subtitle.jsx
> +      '_is-large': size === 'l',
Огонь! 🔥

2020-10-23 15:33 UTC, ArtyomResh commented on components/Post/Body/Subtitle/Subtitle.jsx
> +    size="m"
Давай только небольшой апгрейд сделаем, если прос `size` равен `s` или `m` то его значение идёт сюда на 14 строку, а если l, то в класс на 11. По дефолту `size` будет `m`

2020-10-23 15:33 UTC, ArtyomResh commented on components/Post/Body/Subtitle/Subtitle.jsx
> +  size: string,
Давай тут тип `oneOf` сделаем

2020-10-23 15:33 UTC, ArtyomResh commented on data/categoriesByLanguage.js
> +    news: 'News',
Тут можно удалить, потому что на англ не будет новостей

2020-10-23 15:35 UTC, ArtyomResh commented on data/categoriesByLanguage.js
> +    news: 'News',
Я удалил

2020-10-26 07:27 UTC, dyurein commented on _posts/news512/news-12.md
> +episodeNumber: '#12'
Исправил

2020-10-26 07:39 UTC, dyurein commented on components/Post/Body/NewsAudioLink/NewsAudioLink.styles.js
> +  }
Исправил

2020-10-26 08:00 UTC, dyurein commented on components/Post/Body/Body.jsx
> +            newsHeading_regular_s: type === 'news',
Исправил

2020-10-26 08:22 UTC, dyurein commented on components/Post/Body/ParagraphWithImage/ParagraphWithImage.jsx
> +          'img-wrap_right-side': imageSide === 'right',
Исправил стили на укороченный вариант :)

2020-10-26 08:53 UTC, dyurein commented on components/Post/Body/ParagraphWithImage/ParagraphWithImage.jsx
> +        newsParagraphWithImage: imageSide === 'right',
Переделал с `.with_right-side-image`

2020-10-26 09:17 UTC, dyurein commented on components/Post/Body/Subtitle/Subtitle.jsx
> +    size="m"
Исправил

2020-10-26 09:18 UTC, dyurein commented on components/Post/Body/Subtitle/Subtitle.jsx
> +  size: string,
Добавил

2020-10-26 15:19 UTC, ArtyomResh approved these changes

2020-10-27 08:16 UTC, merged