fix: COM-2901
CSSSR/csssr.blog pull request #294
Opened 2020-10-29 07:59 UTC by dyurein

## Задача
- ссылка на jira: COM-2901
- стенд: http:/fix-com-2901.csssr-new-blog.csssr.cloud/

2020-10-29 15:58 UTC, ArtyomResh requested changes

2020-10-29 15:58 UTC, ArtyomResh commented on _posts/news512/news-12.md
> +<Subtitle size="l">В этом выпуске: путь обучения фронтенду от Mozilla, комбинация флексов и гридов, тестовые задания компаний, материалы по Vue 3, протокол QUIC, релизы PHP-фреймворков, судебные тяжб
Подтяни релизную ветку, я там перенёс это в компонент Head

2020-10-30 07:37 UTC, ArtyomResh requested changes
Теперь в самом файле новости в заголовке нужно «дубль 2» обернуть в спан как ты делал до этого

2020-10-30 08:11 UTC, dyurein commented
@ArtyomResh А как почистить span в мета тайтле?

2020-10-30 12:15 UTC, ArtyomResh approved these changes

2020-10-30 12:21 UTC, merged