[COM-2932]: Fix news number markup
CSSSR/csssr.blog pull request #304
Opened 2020-11-02 14:43 UTC by BenuelBertran

## Задача
- ссылка на jira: COM-2932
- стенд: http://com-2932.csssr-new-blog.csssr.cloud/

## Чек-лист
- [ ] PR в ветку релиза
- [+] Указаны ревьюеры
- [ ] Обновил документацию

2020-11-03 08:10 UTC, dyurein approved these changes

2020-11-03 11:33 UTC, ArtyomResh requested changes

2020-11-03 11:33 UTC, ArtyomResh commented on components/main/Pagination/Pagination.styles.js
> +      margin-top: ${calcRem(170)};
На десктопе не обязательно писать в ремах – это без особой на то надобности усложняет проверку вёрстки, приходится тратить время на [перевод ремов в пиксели](http://s.csssr.ru/U31J879TR/20201103142435.jpg)

2020-11-03 11:33 UTC, ArtyomResh commented on components/main/Posts/PostCard/PostCard.styles.js
> +
Уточни у ребят вот этот момент на всякий случай, обычно они на блоге не пишут отдельные стили для различных разрешений десктопа и всегда рисуют одинаковые стили для всего дестопа, тут возможно они ошиблись

2020-11-03 11:33 UTC, ArtyomResh commented on components/main/Pagination/Pagination.styles.js
> +      margin-top: ${calcRem(170)};
Это скажется на вёрстке на главной, теперь пагинация на той странице будет не на месте. Я не люблю нарушать флоу маргинов (либо всегда отсуп сверху, либо всегда снизу), но иногда приходится. Тут как раз тот самый случай – надо задать маргин снизу от блока со списком новостей

2020-11-05 07:24 UTC, ArtyomResh approved these changes

2020-11-05 10:00 UTC, merged