[COM-2929]: Fix categories styles
CSSSR/csssr.blog pull request #305
Opened 2020-11-02 16:17 UTC by BenuelBertran

## Задача
- ссылка на jira: COM-2929
- стенд: http://com-2929.csssr-new-blog.csssr.cloud/

## Чек-лист
- [ ] PR в ветку релиза
- [+] Указаны ревьюеры
- [ ] Обновил документацию

2020-11-03 08:22 UTC, ArtyomResh commented
Ставь в чекбоксе в описании «x», а не «+» :)

2020-11-03 11:13 UTC, ArtyomResh requested changes

2020-11-03 11:13 UTC, ArtyomResh commented on components/main/MainPage.jsx
> +      <Grid className={className}>
Давай `Grid` лучше положим внутрь `Categories` по аналогии с другими компонентами

2020-11-03 14:59 UTC, BenuelBertran commented on components/main/MainPage.jsx
> +      <Grid className={className}>
При таком решении возникают проблемы на странице News, так как там уже есть общий Grid. 
На MainPage такой проблемы нет, так как там нет общего Grid и есть только три компонента (категории сейчас для этого обёрнуты в Grid), а в Post и Paginations есть свой Grid, как ты правильно заметил. 

В News же стоит общий Grid для Categories, заголовка и обёртки с информацией о новости. А NavList и Pagination стоят отдельно, так как у них Grid свой. 

Таким образом, если делать Grid в Components, то на странице News получается Grid в Grid и вёрстка ломается. 
Если же для блока с информацией о новости отдельно сделать обёртку и её обернуть в Grid, то блок выравнивается верно, НО едет картинка, которая была привязана к общему Grid для Components и блоку с информацией. 

В оооообщем, нужно или оставить как есть или ещё поэкспериментировать....

2020-11-03 15:07 UTC, BenuelBertran commented on components/main/MainPage.jsx
> +      <Grid className={className}>
Кое-что придумал. Пробую. Пока не ревьюй

2020-11-05 07:27 UTC, ArtyomResh approved these changes

2020-11-05 10:32 UTC, merged