Feat/com 2894
CSSSR/csssr.blog pull request #377
Opened 2020-12-21 07:29 UTC by dyurein

## Checklist
- [x] PR is directed to the release branch (if there is a release branch, otherwise this item can be removed)
- [ ] Code meets requirements not only from the description of the task, but also from its comments
- [x] Code works correctly on all resolutions
- [ ] Task completed with comments for testing (if necessary, otherwise this item can be removed)
- [x] Browser dev tools has no errors
- [ ] Got acquainted with the project documentation and updated it if necessary

2020-12-23 12:01 UTC, BenuelBertran commented on _posts/ru/unplug-yourself-csssr-edition.md
>    <p> Сейчас, конечно, я не смогу даже дня без телефона:</p>
Проверь, пожалуйста для этой статьи наличие и корректное описание картинки из шапки и правильный отступ в первом абзаце ("многие зарубежные авторы..." прилип к "Этот пост посвящается...").

2020-12-23 14:07 UTC, dyurein commented on _posts/ru/ng-options.md
> +author: 'Islam Vindizhev'
+

2020-12-23 14:33 UTC, dyurein commented on _posts/ru/ng-options.md
> +***Warning: статья для начинающих и сочувствующих!***
![image](https://user-images.githubusercontent.com/37905737/103007727-f8407a80-4544-11eb-82e9-8b4dfb9c6a76.png)
Отступ есть

2021-01-11 12:16 UTC, dyurein commented on _posts/ru/ng-options.md
> +coverImageAlt: 'alt me'
+

2021-01-11 12:24 UTC, dyurein commented on _posts/ru/npm-init.md
> +coverImageAlt: 'alt me'
+

2021-01-11 12:28 UTC, dyurein commented on _posts/ru/planes.md
> +coverImageAlt: 'Неудобства коллективной работы.'
+

2021-01-11 13:11 UTC, dyurein commented on components/Post/Body/Body.styles.js
> +  code + a {
Убрал

2021-01-12 13:50 UTC, ArtyomResh commented on _posts/ru/react-map-performance.md
> +<p class="paragraph_big-letter">**Ч**асто при написании компонентов приходится использовать мапы для рендера списков.</p>
А почему тут без `<p class="paragraph_big-letter">` не получилось? В других статьях всё ок, в чём тут была проблема?

2021-01-12 14:02 UTC, ArtyomResh requested changes

2021-01-12 14:02 UTC, ArtyomResh commented on _posts/ru/react-map-performance.md
> +<p class="paragraph_big-letter">**Ч**асто при написании компонентов приходится использовать мапы для рендера списков.</p>
Если у тебя суть класса заключается в том, что бы задать минимальную высоту, то эту суть и отрази в названии, т.е. вместо `paragraph_big-letter` лучше сделать `paragraph_with_min-height`. Проблема в том, что сейчас я вижу  `paragraph_big-letter` и думаю, а почему только у трёх статей есть такой класс, а не у всех, ведь в каждой статье есть такой параграф и если я буду писать новую статью, то мне будет не совсем понятно как же мне нужно делать. И если ты добавляешь класс, то нужно тогда и в доке этого компонента это отразить. В общем, получается довольно геморно. Я бы на твоём месте просто инлайново прописал бы эти стили, потому что, пока что из 36 статей только в 3 понадобился этот класс — больше похоже на исключение из правил, чем на закономерность, которую нужно прописать

2021-01-12 14:36 UTC, dyurein commented on _posts/ru/react-map-performance.md
> +<p class="paragraph_big-letter">**Ч**асто при написании компонентов приходится использовать мапы для рендера списков.</p>
![image](https://user-images.githubusercontent.com/37905737/104328175-9dbf8c00-54fc-11eb-8ef7-2d225af9dbad.png)
Абзацы слипались из за нехватки текста в первом параграфе

2021-01-12 14:37 UTC, dyurein commented on _posts/ru/react-map-performance.md
> +<p class="paragraph_big-letter">**Ч**асто при написании компонентов приходится использовать мапы для рендера списков.</p>
Исправил на инлайновые

2021-01-13 12:58 UTC, ArtyomResh approved these changes

2021-01-13 13:39 UTC, merged