fix: COM-2989 Remove double scroll
CSSSR/csssr.blog pull request #397
Opened 2021-01-13 13:02 UTC by dyurein

* jira release board: https://jira.csssr.io/projects/COM/versions/12406
* testing: http://release-blog-after-ny.csssr.cloud

## Checklist
- [x] PR is directed to the release branch (if there is a release branch, otherwise this item can be removed)
- [ ] Code meets requirements not only from the description of the task, but also from its comments
- [x] Code works correctly on all resolutions
- [ ] Task completed with comments for testing (if necessary, otherwise this item can be removed)
- [x] Browser dev tools has no errors
- [ ] Got acquainted with the project documentation and updated it if necessary

2021-01-13 15:12 UTC, ArtyomResh requested changes

2021-01-13 15:12 UTC, ArtyomResh commented on components/Post/Post.styles.js
> -
Тут ты удаляешь `overflow-x: hidden;` в компонент `Post`, который у нас используется на 36+ страницах — большая вероятность что-то сломать. В таком случае лучше посмотреть с помощью ` git blame`, когда и при каких условиях появился этот кусочек кода. В данном случае это кусочек добавил ты сам, когда делал задачу COM-1931, в рамках этой задачи ты добавил несколько новых статей на блог, если одна из них это [Augmented & Virtual Reality to Shape the Future of Web Development](https://fix-com-2989.csssr-new-blog.csssr.cloud/en/article/augmented-and-virtual-reality/), у которой теперь появился горизонтальный скролл после твоих изменений в этом коммите. Значит текущее решение не подойдёт, надо придумать что-то другое

2021-01-14 08:01 UTC, dyurein commented on components/Post/Post.styles.js
> -
Поменять на overflow: hidden, должно работать все гуд

2021-01-14 08:23 UTC, ArtyomResh approved these changes

2021-01-14 09:06 UTC, merged