fix: COM-3056 Horizontal scroll fix
CSSSR/csssr.blog pull request #398
Opened 2021-01-13 13:51 UTC by dyurein

* jira release board: https://jira.csssr.io/projects/COM/versions/12703
* testing: http://release-blog-year-results.csssr.cloud

## Checklist
- [x] PR is directed to the release branch (if there is a release branch, otherwise this item can be removed)
- [ ] Code meets requirements not only from the description of the task, but also from its comments
- [x] Code works correctly on all resolutions
- [ ] Task completed with comments for testing (if necessary, otherwise this item can be removed)
- [x] Browser dev tools has no errors
- [ ] Got acquainted with the project documentation and updated it if necessary

2021-01-13 15:17 UTC, ArtyomResh requested changes

2021-01-13 15:17 UTC, ArtyomResh commented on components/Newsletter/Newsletter.jsx
> +      <Global styles={mainStyles} />
Думаю тут можешь просто в общих стилях на `.main` добавить `overflow: hidden;`, `Global` тут не особо нужен

2021-01-13 15:17 UTC, ArtyomResh commented on components/Newsletter/Newsletter.jsx
> +            alt={imgAlt}f
![F](https://www.meme-arsenal.com/memes/a2f3642489d61e797c75a271dbbf8347.jpg) 
:D

2021-01-14 07:25 UTC, dyurein commented on components/Newsletter/Newsletter.jsx
> +            alt={imgAlt}f
**F**

2021-01-14 07:32 UTC, dyurein commented on components/Newsletter/Newsletter.jsx
> +            alt={imgAlt}f
Исправил

2021-01-14 08:22 UTC, ArtyomResh approved these changes

2021-01-14 09:05 UTC, merged