[COM-3046]: Fixed doubled commento block
CSSSR/csssr.blog pull request #429
Opened 2021-02-02 12:06 UTC by BenuelBertran

## Checklist
- [ ] Code meets requirements not only from the description of the task, but also from its comments
- [ ] Code works correctly on all resolutions
- [ ] Browser dev tools has no errors
- [ ] Got acquainted with the project documentation and updated it if necessary

2021-02-03 08:45 UTC, ArtyomResh commented on components/Post/Body/Comments/Comments.jsx
> +  }, [language, id]);
Интересный хак, где ты о нём прочёл?

2021-02-03 08:45 UTC, ArtyomResh commented on components/Post/Body/Comments/Comments.jsx
> +    <div id="commento-container" className={className}>
Не вижу что бы где-то в коде фикса это использовалось, для чего это тут?

2021-02-03 08:45 UTC, ArtyomResh commented on components/Post/Body/Comments/Comments.jsx
> +  }
Почему тут нельзя просто удалить сразу весь контейнер с id `commento`? Он же по идее создаётся скриптом, и если удалишь, то он создаст новый

2021-02-03 09:12 UTC, BenuelBertran commented on components/Post/Body/Comments/Comments.jsx
> +  }, [language, id]);
Человек писал на форумах о похожей проблеме у себя на сайте, по счастливой случайности также со статичной генерацией на нексте, в итоге запилил свой гайд у себя https://www.kiteframe.co.uk/guides/integrating-commento

2021-02-03 09:13 UTC, BenuelBertran commented on components/Post/Body/Comments/Comments.jsx
> +  }
Контейнер с id комменто, добавляет не скрипт. Он нужен как раз, чтобы скрипт знал куда добавлять содержимое. p.s. если удалять сам контейнер через функцию в useEffect, то всё ломается.

2021-02-04 07:36 UTC, ArtyomResh commented on components/Post/Body/Comments/Comments.jsx
> +  }, [language, id]);
Оставь тогда в коде коммент с этой ссылкой

2021-02-04 07:38 UTC, ArtyomResh requested changes

2021-02-04 07:38 UTC, ArtyomResh commented on components/Post/Body/Comments/Comments.jsx
> +  //This part allows comments in development mode
Оставь тут тогда коммент с ссылкой где ты прочёл об этом решении

2021-02-04 07:39 UTC, ArtyomResh commented on components/Post/Body/Comments/Comments.jsx
> +  //This part allows comments in development mode
Лучше всего оригинал https://remysharp.com/2019/06/11/ejecting-disqus на который ссылаются в той статье, что ты скинул мне https://www.kiteframe.co.uk/guides/integrating-commento

2021-02-05 07:45 UTC, ArtyomResh approved these changes

2021-02-10 13:14 UTC, merged