release: BLOG-EMAIL-SUBSCRIBE
CSSSR/csssr.blog pull request #434
Opened 2021-02-05 09:28 UTC by dyurein

## Release (if there is a release branch, otherwise this header and the paragraph below can be removed).
* jira release board: https://jira.csssr.io/projects/COM/versions/12721
* testing: http://release-blog-email-subscribe.csssr.cloud

2021-02-12 08:22 UTC, ArtyomResh approved these changes

2021-02-18 13:53 UTC, ArtyomResh requested changes

2021-02-18 13:53 UTC, ArtyomResh commented on components/PostNewsletter/PostNewsletter.jsx
> +  console.log(isBottomPosition)
Удали

2021-02-18 13:53 UTC, ArtyomResh commented on components/FooterWrapper/FooterWrapper.jsx
> +const FooterWrapper = ({ preset, type, language, setBottomPossition }) => {
```suggestion
const FooterWrapper = ({ preset, type, language, setBottomPosition }) => {
```

2021-02-18 13:53 UTC, ArtyomResh commented on components/ContactForm/FormStateMessage/FormStateMessage.styles.js
> +}
```suggestion
const StyledFormStateMessage = (props) => {
  const { breakpoints } = props.theme

  return css`
    ${base({ breakpoints })}
  `
}

export default StyledFormStateMessage
```
Для того что бы не было [вот таких сообщений](http://s.csssr.ru/U31J879TR/2021-02-18-16-29-37-95h0q_.jpg) в консоли и терминале

2021-02-18 13:53 UTC, ArtyomResh commented on components/FooterWrapper/FooterWrapper.styles.js
> +}
Если никаких стилей нет, то и не пиши их

2021-02-18 13:53 UTC, ArtyomResh commented on components/ContactForm/FormStateMessage/FormStateMessage.styles.js
> +}
Проверь дургие экспорты из стилей

2021-02-18 14:16 UTC, dyurein commented on components/ContactForm/FormStateMessage/FormStateMessage.styles.js
> +}
Исправил

2021-02-18 14:16 UTC, dyurein commented on components/FooterWrapper/FooterWrapper.jsx
> +const FooterWrapper = ({ preset, type, language, setBottomPossition }) => {
Исправил

2021-03-04 15:21 UTC, ArtyomResh commented on components/ContactForm/ContactForm.jsx
> +        if (!data['FINAL_FORM/form-error']) {
@dyurein Я проверил другие формы на других проектах и не увидел что бы у нас вообще когда-либо работал ресет. В общем, тут была ошибка из-за того, что после резолва промиса данные брались `submitSucceeded` брались не актуальные, а старые из замыкания. Поэтому заменил проверку на проверку отсутствия ошибок в объекте, который возвращает onSubmit функция. Если таких ошибок нет, значит всё прошло как надо

2021-03-05 13:12 UTC, dyurein commented on components/ContactForm/ContactForm.jsx
> +        if (!data['FINAL_FORM/form-error']) {
Понял, спасибо

2021-03-18 13:03 UTC, merged