feat: COM-3131 Update position of subscribe block on main page
CSSSR/csssr.blog pull request #436
Opened 2021-02-05 14:22 UTC by dyurein

## Release (if there is a release branch, otherwise this header and the paragraph below can be removed).
* jira release board: https://jira.csssr.io/projects/COM/versions/12721
* testing: http://release-blog-email-subscribe.com.csssr.cloud

## Checklist
- [ ] PR is directed to the release branch (if there is a release branch, otherwise this item can be removed)
- [ ] Code meets requirements not only from the description of the task, but also from its comments
- [ ] Code works correctly on all resolutions
- [ ] Task completed with comments for testing (if necessary, otherwise this item can be removed)
- [ ] Browser dev tools has no errors
- [ ] Got acquainted with the project documentation and updated it if necessary

2021-02-08 07:41 UTC, ArtyomResh requested changes

2021-02-08 07:41 UTC, ArtyomResh commented on components/Layout/Layout.styles.js
> +      padding-bottom: ${calcRem(20)};
Давай этот padding-bottom и тот что на 88 строке пенесём из Layout.styles от main к блоку Newsletters. Там недостаточный паддинг снизу для того что бы влезала картинка

2021-02-09 12:36 UTC, dyurein commented on components/Layout/Layout.styles.js
> +      padding-bottom: ${calcRem(20)};
Тут сейчас правильно :) По макету нога выходит за границу блока подписки 
![image](https://user-images.githubusercontent.com/37905737/107364472-87e9ba80-6aec-11eb-8f25-4a9ddf57b686.png)
@ArtyomResh

2021-02-10 07:53 UTC, ArtyomResh commented on components/Layout/Layout.styles.js
> +      padding-bottom: ${calcRem(20)};
Да, я понимаю что она должна выходить, но нужно добавить нужный паддинг для того что бы она выходила это ответственность самого блока, в котором это изображение находится, а не main страницы, на которой находится этот блок. Блок с этим изображением должен быть самодостаточным, иначе везде где он будет вставляться придется менять паддинги у родителей

2021-02-10 07:58 UTC, ArtyomResh requested changes
Вот об этом я говорю http://s.csssr.ru/U31J879TR/2021-02-10-10-55-10-n9fgb.mp4

2021-02-11 14:05 UTC, dyurein commented on components/Layout/Layout.styles.js
> +      padding-bottom: ${calcRem(20)};
Понял, исправил

2021-02-12 07:57 UTC, ArtyomResh requested changes

2021-02-12 07:57 UTC, ArtyomResh commented on components/Newsletter/Newsletter.styles.js
> +      margin-bottom: ${calcRem(20)};
Всё круто, но только давай эти значения запишем в padding-bottom :)

2021-02-15 12:24 UTC, ArtyomResh requested changes
Реши конфликты

2021-02-15 13:22 UTC, merged