feat: COM-3132 Update subscribe block in article page
CSSSR/csssr.blog pull request #445
Opened 2021-02-09 12:20 UTC by dyurein

## Release (if there is a release branch, otherwise this header and the paragraph below can be removed).
jira release board: https://jira.csssr.io/projects/COM/versions/12721
testing: http://release-blog-email-subscribe.com.csssr.cloud

## Checklist
- [x] PR is directed to the release branch (if there is a release branch, otherwise this item can be removed)
- [ ] Code meets requirements not only from the description of the task, but also from its comments
- [x] Code works correctly on all resolutions
- [ ] Task completed with comments for testing (if necessary, otherwise this item can be removed)
- [x] Browser dev tools has no errors
- [ ] Got acquainted with the project documentation and updated it if necessary

2021-02-12 07:51 UTC, ArtyomResh reviewed
В целом мне понравилось как ты всё сделал, хорошая работа! Но есть замечания :)

2021-02-12 07:51 UTC, ArtyomResh commented on package-lock.json
> +{
В каждом проекте должен быть либо yanr.lock, либо package-lock.json, но никак не обах. Если видишь yarn.lock, то значит устанавливай всё с помощью команды `yarn add`, если видишь package-lock.json, то с помощью `npm install`. На проекте уже был yarn.lock, поэтому удали этот файл и переустанови react-share с помощью yarn

2021-02-12 07:51 UTC, ArtyomResh commented on components/PostShare/PostShare.jsx
> +      inputRef.current.select() // для локальной работы копирования текста
👍

2021-02-12 07:51 UTC, ArtyomResh commented on components/PostNewsletter/PostNewsletter.styles.js
> +      transform: translateX(calc((100vw - ${calcRem(624)}) / 4 - ${calcRem(78)}));
Когда пишешь такие сложные формулы, то оставляй комменты, что бы человеку, который стокнется с этим впервые было понятно что это форма делает, для чего она нужно, и что каждый из операндов значит

2021-02-12 07:51 UTC, ArtyomResh commented on components/PostNewsletter/PostNewsletter.jsx
> +      inTop: isTopPosition
```suggestion
      onBottom: isBottomPosition,
      onTop: isTopPosition
```

2021-02-12 07:51 UTC, ArtyomResh commented on components/Post/Header/Header.jsx
> +      entry.isIntersecting ? setTopPosition(true) : setTopPosition(false)
```suggestion
      setTopPosition(entry.isIntersecting)
```

2021-02-12 07:51 UTC, ArtyomResh commented on components/Post/Header/Header.jsx
> +  const postType = type
Лучше не называть одно и тоже двумя разными переменными, это плодит лишние абстракции, которые усложняют понимание кода

2021-02-12 07:51 UTC, ArtyomResh commented on components/Post/Header/Header.jsx
> +    const langThreshold = (language === 'ru' && postType !== 'news') ? '1' : '0'
Условие вынеси в переменную и переиспользуй

2021-02-12 07:51 UTC, ArtyomResh commented on components/Post/Header/Header.jsx
> +    const langThreshold = (language === 'ru' && postType !== 'news') ? '1' : '0'
И пусть название переменных будут margin и threshold, тогда ты избежишь название одного и того же двумя разными названиями и сможешь зашорхендить эти перменные в объекте options

2021-02-12 07:51 UTC, ArtyomResh commented on components/Post/Body/Comments/Comments.jsx
> +    }
Здесь аналогично тому что я писал в Header

2021-02-12 07:51 UTC, ArtyomResh commented on components/Post/Body/Comments/Comments.jsx
> +    }
Смотри что происходит http://s.csssr.ru/U31J879TR/2021-02-12-10-27-34-ogtl6.mp4 
На ру такого нет, это связанно с тем что у тебя разные трешхолды и маргины для языков и статей. Они точно должны быть разными? Если должны, то отпишись тут в комментах почему они разные, чем это обусловленно. Поиграйся со значением -500рx что бы такого не происходило

2021-02-12 07:51 UTC, ArtyomResh commented on components/Newsletter/Newsletter.styles.js
> +
Не похоже что это где-то используется

2021-02-12 07:51 UTC, ArtyomResh commented on components/ContactForm/FormStateMessage/FormStateMessage.jsx
> +              <span className="reset-button" onClick={() => onTryAgain()}>Попробуйте<br/> еще раз</span>
```suggestion
              <span className="reset-button" onClick={onTryAgain}>Попробуйте<br/> еще раз</span>
```

2021-02-12 07:51 UTC, ArtyomResh commented on components/ContactForm/FormStateMessage/FormStateMessage.jsx
> +  }
```suggestion
  const getMessage = () => {
    if (status === 'success') {
      return 'Ура! Вы подписались на рассылку.',
    } 
    
    if (status === 'fail') {
      return 'Упс, что-то пошло не так.',
    }
    
    return null
  }
```

2021-02-12 07:51 UTC, ArtyomResh commented on components/ContactForm/FormStateMessage/FormStateMessage.jsx
> +            {textData.message}
```suggestion
            {getMessage()}
```

2021-02-12 07:51 UTC, ArtyomResh commented on components/ContactForm/FormStateMessage/FormStateMessage.jsx
> +  errorText: string,
Тут прописан, но не вижу что бы где-то использовался в компоненте

2021-02-12 07:51 UTC, ArtyomResh commented on components/ContactForm/ContactForm.jsx
>              errorText={submitError}
Тут прописан, но не вижу что бы где-то использовался в компоненте

2021-02-12 07:51 UTC, ArtyomResh commented on components/ContactForm/ContactForm.jsx
> +
Лишний пробел

2021-02-12 07:51 UTC, ArtyomResh commented on components/ContactForm/ContactForm.jsx
> +            visible: isFocused
Давай тут без JS обойдёмся напиши с помощью css стиль `.email::focused ~ .policy { ... }`

2021-02-12 07:52 UTC, ArtyomResh requested changes
В целом мне понравилось как ты всё сделал, хорошая работа! Но есть замечания :)

2021-02-12 09:58 UTC, dyurein commented on public/icons/share/hover/vk.svg
> +<rect width="24" height="24" fill="#F2F2F8"/>
Исправил

2021-02-12 10:04 UTC, dyurein commented on package-lock.json
> +{
Понял, исправил

2021-02-12 11:13 UTC, dyurein commented on components/PostNewsletter/PostNewsletter.styles.js
> +      transform: translateX(calc((100vw - ${calcRem(624)}) / 4 - ${calcRem(78)}));
Добавил к одному, в desktop.l

2021-02-12 11:19 UTC, dyurein commented on components/PostNewsletter/PostNewsletter.jsx
> +      inTop: isTopPosition
Исправил

2021-02-12 12:41 UTC, dyurein commented on components/Post/Header/Header.jsx
> +      entry.isIntersecting ? setTopPosition(true) : setTopPosition(false)
Хорошее исправление

2021-02-12 12:45 UTC, dyurein commented on components/Post/Header/Header.jsx
> +  const postType = type
Понял, просто в каком то компоненте уже так было сделано, взял от туда

2021-02-12 13:04 UTC, dyurein commented on components/Post/Header/Header.jsx
> +    const langThreshold = (language === 'ru' && postType !== 'news') ? '1' : '0'
Исправил

2021-02-12 13:14 UTC, dyurein commented on components/Post/Body/Comments/Comments.jsx
> +    }
Менял как раз чтобы такого не происходило,  у меня разные тресхолды фиксили такое поведение. Посмотрю еще раз

2021-02-12 13:19 UTC, dyurein commented on components/Post/Body/Comments/Comments.jsx
> +    }
https://user-images.githubusercontent.com/37905737/107772870-dd70d200-6d4d-11eb-984c-4601421a187f.mp4
У меня блок не лезет в футер

2021-02-12 13:21 UTC, dyurein commented on components/Newsletter/Newsletter.styles.js
> +
Точно, забыл убрать

2021-02-12 13:30 UTC, dyurein commented on components/ContactForm/FormStateMessage/FormStateMessage.jsx
> +              <span className="reset-button" onClick={() => onTryAgain()}>Попробуйте<br/> еще раз</span>
Исправил

2021-02-12 13:40 UTC, dyurein commented on components/ContactForm/FormStateMessage/FormStateMessage.jsx
> +  }
Исправил

2021-02-12 14:00 UTC, dyurein commented on components/ContactForm/FormStateMessage/FormStateMessage.jsx
> +  errorText: string,
Убрал

2021-02-12 14:05 UTC, dyurein commented on components/ContactForm/ContactForm.jsx
>              errorText={submitError}
Убрал

2021-02-12 14:08 UTC, dyurein commented on components/ContactForm/ContactForm.jsx
> +
Убрал

2021-02-12 15:01 UTC, dyurein commented on components/ContactForm/ContactForm.jsx
> +            visible: isFocused
С помощью css тут не достает по структуре
![image](https://user-images.githubusercontent.com/37905737/107783858-c507b400-6d5b-11eb-9250-3464d5899331.png)

2021-02-15 08:28 UTC, ArtyomResh requested changes

2021-02-15 08:28 UTC, ArtyomResh commented on components/ContactForm/ContactForm.jsx
> +            visible: isFocused
Да, ты прав, не обратил внимание, тогда давай `onFocus={() => setFocused(true)}` уберём с дива и повесим его на настоящий интерактивный элемент - TextField

2021-02-15 08:28 UTC, ArtyomResh commented on components/PostNewsletter/PostNewsletter.styles.js
> +      transform: translateX(calc((100vw - 656px) / 4 - 78px)); // От ширины экрана отнимается ширина контента, делится на 4 (отступ в левой части от конента) и отнимаем половину ширины блока подписки
В следующий раз оставляй коммент прям в каждом месте где эта формула повторяется

2021-02-15 08:28 UTC, ArtyomResh commented on components/Post/Header/Header.jsx
> +    const langAndPostCondition = (language === 'ru' && type !== 'news')
Хитро :)

2021-02-15 08:28 UTC, ArtyomResh commented on components/Post/Body/Comments/Comments.jsx
> +    }
Это потому что у тебя блок с комментами остаётся в пределах экрана, но если его вывести за пределы, то подписка налезает на футер. Надо посмотреть как это будет работать с фиксом от Саши, который включает комменты на тестах и разработке, но пока запомни что такой баг есть и надо будет его обязательно проверить

2021-02-15 08:28 UTC, ArtyomResh commented on components/PostShare/PostShare.styles.js
> +        }
Я думаю это тебе тут не нужно, ты же прописал fill: currentColor прямо в самих svg

2021-02-15 09:02 UTC, dyurein commented on components/PostNewsletter/PostNewsletter.styles.js
> +      transform: translateX(calc((100vw - 656px) / 4 - 78px)); // От ширины экрана отнимается ширина контента, делится на 4 (отступ в левой части от конента) и отнимаем половину ширины блока подписки
Добавил

2021-02-15 09:04 UTC, dyurein commented on components/PostShare/PostShare.styles.js
> +        }
Убрал

2021-02-15 12:18 UTC, ArtyomResh approved these changes

2021-02-15 12:19 UTC, merged