[COM-3192]: Styling comments block
CSSSR/csssr.blog pull request #449
Opened 2021-02-11 16:46 UTC by BenuelBertran

## Release (if there is a release branch, otherwise this header and the paragraph below can be removed).
* jira release board: https://jira.csssr.io/projects/COM/versions/12731
* testing: http://release-Blog-comments-style.csssr.cloud

## Checklist
- [x] PR is directed to the release branch (if there is a release branch, otherwise this item can be removed)
- [x] Code meets requirements not only from the description of the task, but also from its comments
- [x] Code works correctly on all resolutions
- [ ] Browser dev tools has no errors

2021-02-12 06:54 UTC, ArtyomResh requested changes

2021-02-12 06:54 UTC, ArtyomResh commented on components/Post/Body/Comments/Comments.jsx
> +let totalComments = 1
Может быть и 0

2021-02-12 06:54 UTC, ArtyomResh commented on components/Post/Body/Comments/Comments.jsx
> +}
Как ты уже понял без слушателя появляения новых комментов у тебя не получится обновлять значение в рилтайме. Даже если бы был, всё равно так делать было бы не совсем правильно. Потому что страницу может открыть одновременно несколько пользователей и они могут начать писать комментарии и если ты будешь считать количество комментариев на их страницах, то у всех может получиться разное число. В таких случаях нужно работать с БД, где хранятся эти комменты и считать их там. 

В любом случае если сами комменты не появляются в рилтайме, то и менять счетчик не нужно. 

Попробуй сделать счетчик по доке комменто – https://docs.commento.io/configuration/frontend/count.html#displaying-comment-count-links

Я оставил тебе коммент на одной из страниц, что бы ты мог поэксперементировать с реплаями
https://com-3192.csssr-new-blog.csssr.cloud/en/article/how-close-your-outsourced-team-should-be-located-pros-and-cons/#commento-login-box-container

2021-02-17 15:56 UTC, ArtyomResh requested changes
Ещё [есть проблема](http://s.csssr.ru/U31J879TR/2021-02-17-18-38-48-apf0a.mp4) из-за того, что window.paren.location.host был изменён на продовый комменты теперь повторяются и на проде
```
window.parent = {
      location: {	      
        host: 'https://blog.csssr.com/',
        pathname: `${language}/article/${id}`,
      },
    }
```
Что бы такого не было измени pathname, добавь к нему на конце `-test`. И в идеале, я бы выбил ещё час времени, что бы заменить хак c window.parent на [самостоятельный хостинг файла скрипта commentо и добавлением к нему дополнительных переменных](https://remysharp.com/2019/06/11/ejecting-disqus#alternative-self-hosted-solution)

2021-02-17 15:56 UTC, ArtyomResh commented on components/Post/Body/Comments/Comments.jsx
> +      document.getElementById("commento-comments-counter").setAttribute("data-custom-text", "window.commentoCustomText");
Идея прикольная :) 
но работает [через раз](http://s.csssr.ru/U31J879TR/2021-02-17-18-35-57-4b38y.mp4)

И смотри какая ещё проблема с этим счётчиком — он изначально показывает какое-то непонятное число. Насколько я понимаю, он показывает количество вообще всех комментариев, даже удалённых. Попробуй погуглить может быть у скрипта есть какие-то дополнительные настройки?

2021-02-18 14:53 UTC, BenuelBertran commented
Убрал весь функционал счётчика, разделил добавление комментариев для прода и теста, включил панель управления с иконками редактирования и удаления собственного комментария, заменил иконки на новые. 
Полный список изменений можно посмотреть в комментах к задаче: https://jira.csssr.io/browse/COM-3192

2021-02-19 07:45 UTC, ArtyomResh approved these changes

2021-02-19 07:52 UTC, merged