Создал статью: CSS Grid: Практические примеры
CSSSR/csssr.blog pull request #470
Opened 2021-02-26 16:12 UTC by nekitk

## Release (if there is a release branch, otherwise this header and the paragraph below can be removed).
* jira release board: https://jira.csssr.io/projects/COM/versions/__HERE_JIRA_VERSION_ID__
* testing: http://release-__HERE_JIRA_RELEASE_ID__.csssr.cloud

## Checklist
- [ ] `data-testid` attribute has been set for new components and interactive blocks according to [documentation](https://github.com/CSSSR/e2e-tools/blob/master/docs/DATA_TESTID.md) 
- [ ] PR is directed to the release branch (if there is a release branch, otherwise this item can be removed)
- [ ] Code meets requirements not only from the description of the task, but also from its comments
- [ ] Code works correctly on all resolutions
- [ ] Task completed with comments for testing (if necessary, otherwise this item can be removed)
- [ ] Browser dev tools has no errors
- [ ] Got acquainted with the project documentation and updated it if necessary

## Optional (if you have something to add, otherwise this heading and the paragraph below can be removed)
* comments to the problem solving
* documentation on added libraries
* screenshots

2021-03-01 08:04 UTC, ArtyomResh requested changes
Не обязательно все изображения внутри статьи класть в `dont-resize`. Для старых статей мы так делали, потому что там было много картинок небольшого разрешения и если мы их обрабатывали, они становились уж совсем мелкими. Если у тебя большие изображения или ты их можешь сделать большими, то можешь класть их в resize, что бы они проходили через обработку. 

https://article-css-grid.csssr-new-blog.csssr.cloud/ru — изображения не прогружаются, отписался об этом в [тред в слаке](https://csssr.slack.com/archives/CH61D6QFL/p1614356981029200). Будем разбираться в чем дело

2021-03-01 08:06 UTC, ArtyomResh commented on postsOrderRu.json
>    ["year-resume-2020", "news512"],
А так прикольно что две положил рядом, можно сразу посмотреть как будет выглядеть изображение для маленькой и большой карточек :)

2021-03-01 08:10 UTC, nekitk commented on postsOrderRu.json
>    ["year-resume-2020", "news512"],
я это не сам делал - это скрипт `yarn article` добавляет сразу 2 одинаковых элемента в 1 строку

мне нужно весь список руками перебрать получается?

2021-03-01 11:21 UTC, nekitk commented
@ArtyomResh гифку поправил, порядок постов в json тоже

заодно поправил механизм упорядочивания постов в json, чтобы не надо было руками их переставлять

2021-03-02 07:54 UTC, ArtyomResh commented
> @ArtyomResh гифку поправил, порядок постов в json тоже
> 
> заодно поправил механизм упорядочивания постов в json, чтобы не надо было руками их переставлять

@nekitk А ререквестнуть ревью забыл :D 
Сегодня посмотрю :)

2021-03-02 08:00 UTC, ArtyomResh requested changes

2021-03-02 08:00 UTC, ArtyomResh commented on scripts/articleTemplate/addNewPost.test.js
> +describe('addNewPost', () => {
Спасибо что написал тест!  :)

2021-03-02 08:02 UTC, ArtyomResh commented
Подмержи себе ещё мастер, там Макс залил правку, которая исправляет загрузку изображений на тестовых стендах

2021-03-02 08:29 UTC, nekitk commented on postsOrderRu.json
> +  ["split-blocks-into-groups", "news512"],
перегенерил json, чтобы не было лишних новостей

2021-03-04 12:02 UTC, ArtyomResh commented on postsOrderRu.json
> +  ["split-blocks-into-groups", "news512"],
Спасибо!

2021-03-04 12:03 UTC, ArtyomResh approved these changes

2021-03-25 09:00 UTC, ArtyomResh approved these changes

2021-03-25 09:00 UTC, merged