feat: COM-3182 Added articles from old blog
CSSSR/csssr.blog pull request #518
Opened 2021-04-01 12:04 UTC by dyurein

## Release (if there is a release branch, otherwise this header and the paragraph below can be removed).
* jira release board: https://jira.csssr.io/projects/COM/versions/12729
* testing: http://release-bl-post-5.csssr.cloud

## Checklist
- [ ] `data-testid` attribute has been set for new components and interactive blocks according to [documentation](https://github.com/CSSSR/e2e-tools/blob/master/docs/DATA_TESTID.md) 
- [x] PR is directed to the release branch (if there is a release branch, otherwise this item can be removed)
- [ ] Code meets requirements not only from the description of the task, but also from its comments
- [ ] Code works correctly on all resolutions
- [ ] Task completed with comments for testing (if necessary, otherwise this item can be removed)
- [ ] Browser dev tools has no errors
- [ ] Got acquainted with the project documentation and updated it if necessary

2021-04-05 07:25 UTC, dyurein commented
@ArtyomResh При добавлении новых статей, добавляется 6 страница, но при переходе на нее выдает 404 страницу. С проблемой не смог разобраться :/

2021-04-05 15:46 UTC, ArtyomResh requested changes
Замени все вставки изображений через ![]() на <Img src='' alt='' withOutProcessing>. Постарайся написать хорошие alt текста

2021-04-05 15:46 UTC, ArtyomResh commented on _posts/ru/managers-qualities.md
> +![EYanovskaya](/images/dont-resize/ru/managers-qualities/eyanovskaya/all.png)
Давай вставим тут изображения так же как мы вставляем в новых статьях, а именно: 
`<Img src='/images/dont-resize/ru/managers-qualities/eyanovskaya/all.png' alt='Фотография Яновской Лизы' withOutProcessing>`

2021-04-05 15:46 UTC, ArtyomResh commented on _posts/ru/managers-qualities.md
> +![EYanovskaya](/images/dont-resize/ru/managers-qualities/eyanovskaya/all.png)
Обрати внимание на alt текст, старайся всегда его делать и делать его хорошо. Думай о том, как бы ты описал увиденное слепому человеку, так что бы он понял что там изображено.

2021-04-05 15:46 UTC, ArtyomResh commented on postsOrderRuFullVersion.json
>  ]
C добавлением последних статей надобность в этом файле отпала, его можно удалить

2021-04-08 08:26 UTC, dyurein commented on postsOrderRuFullVersion.json
>  ]
Удалил

2021-04-09 12:00 UTC, ArtyomResh approved these changes

2021-04-16 07:57 UTC, maksim-kononov-csssr approved these changes

2021-04-20 07:50 UTC, ArtyomResh approved these changes

2021-04-26 08:35 UTC, merged