feat: COM-3422 Added podcast component
CSSSR/csssr.blog pull request #543
Opened 2021-04-09 09:11 UTC by dyurein

## Release (if there is a release branch, otherwise this header and the paragraph below can be removed).
* jira release board: https://jira.csssr.io/projects/COM/versions/__HERE_JIRA_VERSION_ID__
* testing: http://release-__HERE_JIRA_RELEASE_ID__.csssr.cloud

## Checklist
- [ ] `data-testid` attribute has been set for new components and interactive blocks according to [documentation](https://github.com/CSSSR/e2e-tools/blob/master/docs/DATA_TESTID.md) 
- [ ] PR is directed to the release branch (if there is a release branch, otherwise this item can be removed)
- [ ] Code meets requirements not only from the description of the task, but also from its comments
- [ ] Code works correctly on all resolutions
- [ ] Task completed with comments for testing (if necessary, otherwise this item can be removed)
- [ ] Browser dev tools has no errors
- [ ] Got acquainted with the project documentation and updated it if necessary

2021-04-13 06:37 UTC, ArtyomResh requested changes

2021-04-13 06:37 UTC, ArtyomResh commented on components/PostNewsletter/NewsPodcast/NewsPodcast.jsx
> +// import { ReactComponent as FacebookIcon } from '../../public/icons/share/facebook.svg'
Давай удалим если не нужно

2021-04-13 06:37 UTC, ArtyomResh commented on components/PostNewsletter/NewsPodcast/NewsPodcast.jsx
> +        </li>
Положи все элементы списка в массив и замапь их тут

2021-04-13 06:37 UTC, ArtyomResh commented on components/PostNewsletter/PostNewsletter.jsx
>    const withoutSubscribeForm = language !== 'ru' || type === 'news'
Давай вот тут тогда под один вид приведём: 
```suggestion
  const withSubscribeForm = language === 'ru' || type !== 'news'
```
И ниже на 32 строке заменим `!withoutSubscribeForm` на `withSubscribeForm`. 
Лучше всегда стараться в условиях писать булевые значения без `!`, такой код проще читать и поддеживать, потому что убирая оператор `не` мы уменьшаем количество операций на 1

2021-04-13 07:31 UTC, dyurein commented on components/PostNewsletter/PostNewsletter.jsx
>    const withoutSubscribeForm = language !== 'ru' || type === 'news'
Переделал

2021-04-13 12:12 UTC, ArtyomResh requested changes

2021-04-13 12:12 UTC, ArtyomResh commented on components/PostNewsletter/NewsPodcast/NewsPodcast.jsx
> +              href="https://podcasts.apple.com/us/podcast/id1370045815"
Тебе ещё ссылку надо в массив вынести, а то у тебя все сейчас на одну и ту же страницу вести будут

2021-04-13 12:12 UTC, ArtyomResh commented on components/PostNewsletter/PostNewsletter.jsx
> +        'without_subscribe-form': withSubscribeForm,
Тут тогда надо так
```suggestion
        'without_subscribe-form': !withSubscribeForm,
```

2021-04-13 12:53 UTC, dyurein commented on components/PostNewsletter/NewsPodcast/NewsPodcast.jsx
> +              href="https://podcasts.apple.com/us/podcast/id1370045815"
Точно, забыл :/

2021-04-14 08:26 UTC, dyurein commented on components/PostNewsletter/PostNewsletter.jsx
> +        'without_subscribe-form': withSubscribeForm,
Исправил

2021-04-14 11:39 UTC, ArtyomResh requested changes

2021-04-14 11:39 UTC, ArtyomResh commented on components/PostNewsletter/PostNewsletter.jsx
> +  onBottom,
Представь как ты видишь неизвестный тебе компонент компонент, который называется `Validator` у которого есть пропсы `onLeft` и `onRight`. Сможешь ли ты сходу понять что эти пропсы в нём делают? 

C `onTop` и `onBottom` в `PostNewsletter` такая же история. Посмотрев код, я понял, что эти пропсы используются что бы что-то скрывать на мобилке, тогда их так и следует назвать:
`onTop` -> `HideShareLinksOnMobile`
`onBottom` -> `HideNewsNewsPodcastOnMobile`

2021-04-14 12:41 UTC, dyurein commented on components/PostNewsletter/PostNewsletter.jsx
> +  onBottom,
Понял, исправил. В неймингах я еще конкретно suck 5head

2021-04-15 07:27 UTC, ArtyomResh approved these changes

2021-04-15 10:01 UTC, merged