feat(components): COM-3432 Add new Error404Page
CSSSR/csssr.blog pull request #547
Opened 2021-04-12 14:10 UTC by vkosinov

## Checklist
- [x] `data-testid` attribute has been set for new components and interactive blocks according to [documentation](https://github.com/CSSSR/e2e-tools/blob/master/docs/DATA_TESTID.md) 
- [x] Code meets requirements not only from the description of the task, but also from its comments
- [x] Code works correctly on all resolutions
- [x] Task completed with comments for testing (if necessary, otherwise this item can be removed)
- [x] Browser dev tools has no errors
- [ ] Got acquainted with the project documentation and updated it if necessary

2021-04-14 11:55 UTC, ArtyomResh requested changes

2021-04-14 11:55 UTC, ArtyomResh commented on components/error/Error404Page.jsx
> +      />
А нам точно нужен хедер на этой странице? Раньше никогда не было. Да и ссылки из правой части дублируют то что можно найти в хедере

2021-04-14 11:55 UTC, ArtyomResh commented on components/error/ErrorPosts/ErrorPostCard/ErrorPostCard.styles.js
> +import { css } from '@emotion/react'
Стили этой карточки не такие как у карточки на главной странице на мобильном разрешении? Может их можно вынести и переиспользовать?

2021-04-14 11:55 UTC, ArtyomResh commented on pages/404.js
> +}
Кажется тут это не нужно, иначе ошибка
```
> Build error occurred
Error: getStaticPaths can only be used with dynamic pages, not '/404'.
Learn more: https://nextjs.org/docs/routing/dynamic-routes
    at /home/runner/work/csssr.blog/csssr.blog/new_blog/node_modules/next/dist/build/utils.js:26:58
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Span.traceAsyncFn (/home/runner/work/csssr.blog/csssr.blog/new_blog/node_modules/next/dist/telemetry/trace/trace.js:5:584) {
  type: 'Error'
}
```

Можно доставать язык из пути, как уже сделанно [тут](https://github.com/CSSSR/csssr.blog/pull/547/files#diff-62947809e048cfb89f3817e87b39361ed07a790f33047d77f6ebc8734b2efaf9R23)

2021-04-14 12:22 UTC, vkosinov commented on components/error/Error404Page.jsx
> +      />
На блоге нет ссылок там у нас посты, http://s.csssr.ru/UJ4QCUXM4/2021-04-14-15-22-01.jpg 
а на .com да будут дублировать уточню этот момент у дизайнеров

2021-04-14 12:25 UTC, vkosinov commented on components/error/ErrorPosts/ErrorPostCard/ErrorPostCard.styles.js
> +import { css } from '@emotion/react'
Другие размеры, + усложнено дополнительной вариативностью (широкий - узкий, новости и т.д.)

2021-04-14 14:26 UTC, vkosinov commented on components/error/Error404Page.jsx
> +    if (isReady) {
Если не дожидаться готовности `route` на русской версии проскакивали английские слова так как по умолчанию проставлялась `en` локаль так как не проходила проверка `ruPathRegexp.test(asPath)`.

Теперь проверка запускается только если готов роутер

2021-04-15 07:22 UTC, vkosinov commented on components/error/Error404Page.jsx
> +      />
Уточнил, нужен https://csssr.slack.com/archives/CG77JR5RN/p1618403243067900

2021-04-15 07:24 UTC, ArtyomResh approved these changes

2021-04-19 09:01 UTC, merged