feat: COM-3350 Removed opacity animation of policy text on mobile
CSSSR/csssr.blog pull request #551
Opened 2021-04-14 15:25 UTC by dyurein

## Checklist
- [ ] `data-testid` attribute has been set for new components and interactive blocks according to [documentation](https://github.com/CSSSR/e2e-tools/blob/master/docs/DATA_TESTID.md) 
- [ ] PR is directed to the release branch (if there is a release branch, otherwise this item can be removed)
- [ ] Code meets requirements not only from the description of the task, but also from its comments
- [x] Code works correctly on all resolutions
- [ ] Task completed with comments for testing (if necessary, otherwise this item can be removed)
- [x] Browser dev tools has no errors
- [ ] Got acquainted with the project documentation and updated it if necessary

2021-04-15 07:21 UTC, ArtyomResh requested changes

2021-04-15 07:21 UTC, ArtyomResh commented on components/ContactForm/ContactForm.jsx
> +        <Fade duration={400} collapse when={isMobile ? true : !isMessageHidden}>
По идее тут из-за того что ты уже прописал в условие на 73 строке `!isMobile` тут его писать не нужно

2021-04-15 12:22 UTC, dyurein commented on components/ContactForm/ContactForm.jsx
> +        <Fade duration={400} collapse when={isMobile ? true : !isMessageHidden}>
@ArtyomResh на 73 только на блюр при клике, но при загрузке страницы будет прятаться

2021-04-16 08:38 UTC, maksim-kononov-csssr commented on components/PostNewsletter/PostNewsletter.jsx
> +  })
useEffect по умолчанию срабатывает каждый рендер, а тут достаточно одного вызова - при монтировании компонента. Из документации:
Если вы хотите запустить эффект и сбросить его только один раз (при монтировании и размонтировании), вы можете передать пустой массив ([]) вторым аргументом.

2021-04-16 08:38 UTC, maksim-kononov-csssr commented on components/PostNewsletter/PostNewsletter.jsx
> +  })
Откуда число 767px?

2021-04-16 08:38 UTC, maksim-kononov-csssr commented on components/ContactForm/ContactForm.jsx
> +        <Fade duration={400} collapse when={isMobile ? true : !isMessageHidden}>
Проблема в том что управление стейтом isMessageHidden приходит из внешнего компонента и не понятно какая там еще логика. Нужно либо просмотреть всю эту логику, либо можно только одно это условие оставить, а изменения на 73 удалить - потому что именно тут последняя точка решения показывать или не показывать сообщение

2021-04-16 09:24 UTC, maksim-kononov-csssr commented on components/ContactForm/ContactForm.jsx
> +        <Fade duration={400} collapse when={isMobile ? true : !isMessageHidden}>
isMobile || !isMessageHidden

2021-04-16 11:12 UTC, dyurein commented on components/ContactForm/ContactForm.jsx
> +        <Fade duration={400} collapse when={isMobile ? true : !isMessageHidden}>
Убрал условие на 73 строке

2021-04-16 12:10 UTC, dyurein commented on components/ContactForm/ContactForm.jsx
> +        <Fade duration={400} collapse when={isMobile ? true : !isMessageHidden}>
Переделал условие на ```isMobile || !isMessageHidden```

2021-04-19 07:54 UTC, ArtyomResh requested changes

2021-04-19 07:54 UTC, ArtyomResh commented on components/PostNewsletter/PostNewsletter.jsx
> +      if (window.matchMedia("(max-width: 767px)").matches) {
Возьми значение прямо из темы, которую мы используем для всех стилей

```
import { Root, defaultTheme } from '@csssr/core-design'
```
и потом используй `defaultTheme.breakpoints.mobile.all`. Там будет лежать `@media (max-width: 767px)`, поэтому надо будет ещё отфильтровать `@media `.

2021-04-26 10:26 UTC, dyurein commented on components/PostNewsletter/PostNewsletter.jsx
> +      if (window.matchMedia("(max-width: 767px)").matches) {
Сделал

2021-04-27 07:08 UTC, ArtyomResh commented on components/PostNewsletter/PostNewsletter.jsx
> +      if (window.matchMedia("(max-width: 767px)").matches) {
🔥

2021-04-27 07:08 UTC, ArtyomResh approved these changes

2021-05-05 07:09 UTC, ArtyomResh commented
@dyurein надо порешать конфликты

2021-05-05 07:10 UTC, ArtyomResh requested changes
@dyurein надо порешать конфликты

2021-05-05 13:25 UTC, ArtyomResh requested changes

2021-05-05 13:25 UTC, ArtyomResh commented on components/PostNewsletter/PostNewsletter.jsx
> +    }
Давай тут ещё вот так сделаем: 
```suggestion
    const checkWindowWidth = () => 
        setMobile(window.matchMedia(defaultTheme.breakpoints.mobile.all.slice('@media '.length)).matches) 
```

2021-05-06 07:55 UTC, ArtyomResh approved these changes

2021-05-11 07:32 UTC, closed without merging

2021-05-11 07:34 UTC, maksim-kononov-csssr approved these changes