feat: COM-3512 Add storybook
CSSSR/csssr.blog pull request #573
Opened 2021-04-23 15:57 UTC by vkosinov

## Checklist
- [ ] `data-testid` attribute has been set for new components and interactive blocks according to [documentation](https://github.com/CSSSR/e2e-tools/blob/master/docs/DATA_TESTID.md) 
- [ ] PR is directed to the release branch (if there is a release branch, otherwise this item can be removed)
- [ ] Code meets requirements not only from the description of the task, but also from its comments
- [ ] Code works correctly on all resolutions
- [ ] Task completed with comments for testing (if necessary, otherwise this item can be removed)
- [ ] Browser dev tools has no errors
- [ ] Got acquainted with the project documentation and updated it if necessary

## Optional (if you have something to add, otherwise this heading and the paragraph below can be removed)
* comments to the problem solving
* documentation on added libraries
* screenshots

2021-04-30 09:33 UTC, ArtyomResh requested changes
[Отписался](https://jira.csssr.io/browse/COM-3512?focusedCommentId=59831&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-59831) в задаче о том что стоит улучшить

2021-05-05 13:31 UTC, vkosinov commented on stories/Table.stories.mdx
> +      contentMdx: dedent`
Да, можно обойтись без него если все теги сделать одной строкой без переносов

2021-05-05 13:56 UTC, ArtyomResh requested changes
- Контент историй в Docs не меняется, но меняется их код – http://s.csssr.ru/U31J879TR/2021-05-05-16-36-40-8nnok.mp4. Похоже args в Story перебивают настройки пользователя.
- Ещё такой вопрос, а source код можно вывести не только в Docs, но и на Canvas истории, где мы с кнобами балуемся, что бы пользователю не приходилось лишние движения делать? 
- Теперь ещё надо доку блога обновить, удалить дублирование док компонентов и ссылку на сторибук оставить, и дописать как этим пользоваться
- Давай контролы по дефолту справа поставим http://s.csssr.ru/U31J879TR/2021-05-05-16-52-38-h46dg_.png?

2021-05-05 13:56 UTC, ArtyomResh commented on stories/utils/getStringAttributes.js
> +      acc += `${item}="${args[item]}" `
Давай немного поправим, что если args[item] это булевое значение, то возвращаем только item, а то сейчас получается вот так http://s.csssr.ru/U31J879TR/2021-05-05-16-41-06-lbrhj_.png

2021-05-05 13:56 UTC, ArtyomResh commented on .storybook/utils/getTransformSource.js
> +  });
🔥 Вот этого не хватало для чёткого форматирования, да?

2021-05-05 13:56 UTC, ArtyomResh commented on .storybook/main.js
> +module.exports = {
Это всё очень похоже на настройки в next.config.js давай дублирующий код вынесем и переиспользуем

2021-05-05 13:56 UTC, ArtyomResh commented on .storybook/preview.js
> +      state: 'open',
Типо source код должен быть сразу открыт?

2021-05-05 13:56 UTC, ArtyomResh commented on .storybook/webpack.config.js
> +   */
🔥

2021-05-06 09:32 UTC, vkosinov commented on stories/Table.stories.mdx
> +      contentMdx: dedent`
Но тогда в поле ввода они будут без форматирования

2021-05-06 09:57 UTC, vkosinov commented on .storybook/preview.js
> +      state: 'open',
Да но к сожалению не сработало (

2021-05-06 13:01 UTC, vkosinov commented
- [x] 1. Контент историй в Docs не меняется, но меняется их код – http://s.csssr.ru/U31J879TR/2021-05-05-16-36-40-8nnok.mp4. Похоже args в Story перебивают настройки пользователя.
- [ ] 2. Ещё такой вопрос, а source код можно вывести не только в Docs, но и на Canvas истории, где мы с кнобами балуемся, что бы пользователю не приходилось лишние движения делать?
> к сожалению такой возможности в готовых кнобах которые удовлетворяли бы наше условие (показывать сформированную строку) пока нет
- [ ] 3. Теперь ещё надо доку блога обновить, удалить дублирование док компонентов и ссылку на сторибук оставить, и дописать как этим пользоваться
- [x] 4. Давай контролы по дефолту справа поставим http://s.csssr.ru/U31J879TR/2021-05-05-16-52-38-h46dg_.png?

2021-05-07 07:44 UTC, ArtyomResh requested changes

2021-05-07 07:44 UTC, ArtyomResh commented on docs/ru/COMPONENTS.md
> +Все компоненты можно посмотреть в [Storybook](https://master.csssr-blog-storybook.csssr.cloud/)
«Все компоненты и их возможные пропсы можно посмотреть в»

И расскажи немного как пользоваться сторибуком, мол тут есть кнобы, а вот тут дока, а в доке есть соурс код, который строится от ваших кнобов, можете поиграться и скопировать его потом в статью

2021-05-07 14:45 UTC, ArtyomResh approved these changes

2021-05-11 12:46 UTC, merged