feat: COM-3566 Update component styles on blog
CSSSR/csssr.blog pull request #596
Opened 2021-05-12 15:22 UTC by vkosinov

## Checklist
- [ ] `data-testid` attribute has been set for new components and interactive blocks according to [documentation](https://github.com/CSSSR/e2e-tools/blob/master/docs/DATA_TESTID.md) 
- [ ] PR is directed to the release branch (if there is a release branch, otherwise this item can be removed)
- [ ] Code meets requirements not only from the description of the task, but also from its comments
- [ ] Code works correctly on all resolutions
- [ ] Task completed with comments for testing (if necessary, otherwise this item can be removed)
- [ ] Browser dev tools has no errors
- [ ] Got acquainted with the project documentation and updated it if necessary

## Optional (if you have something to add, otherwise this heading and the paragraph below can be removed)
* comments to the problem solving
* documentation on added libraries
* screenshots

2021-05-18 08:08 UTC, ArtyomResh requested changes
- Давай в сторибук добавить все контентные блоки, сейчас вижу что не хватает:
  * блока с кодом
  * строки с кодом
- Давай в скрипт создания шаблона строки добавим hr блок.
- В доках списков в сторибуке, у нумерованного списка похоже неправильно подставляется [код](http://s.csssr.ru/U31J879TR/2021-05-18-10-23-46-n2u9q_.png)
- Серая подложка для кода

2021-05-18 08:48 UTC, ArtyomResh commented on components/Post/Body/Promo/Promo.jsx
> +`
<hr/>

2021-05-18 11:55 UTC, vkosinov commented
- [ ] Давай в сторибук добавить все контентные блоки, сейчас вижу что не хватает: блока с кодом, строки с кодом
- [ ] <Promo/> на <hr/>
- [ ] Давай в скрипт создания новой статьи добавим hr блок.
- [ ] Серая подложка для кода
- [ ] В доках списков в сторибуке, у нумерованного списка похоже неправильно подставляется код

2021-05-19 07:26 UTC, ArtyomResh requested changes
- [ ] Чекнуть [отсутпы](http://s.csssr.ru/U31J879TR/2021-05-19-10-23-28-matz7_.png) у строки кода, если мне не изменяет память, то там должны быть небольшие падинги по 4 или 8 пикселей

- [ ] В стори ThematicGap [не правильно стилизуется буквиница](http://s.csssr.ru/U31J879TR/2021-05-19-10-24-58-cls12_.png)
- [ ] Давай для параграфа с буквиницей тоже добавим стори, в которой можно будет менять язык, что бы показать как она выглядит на разных экранах

2021-05-19 07:26 UTC, ArtyomResh commented on .storybook/utils/getTransformSource.js
> +    return `<${getComponentName(kind)} ${getStringAttributes(args)}/>`;
Это можно объединить с 11-12 строчкой

2021-05-19 07:26 UTC, ArtyomResh commented on .storybook/utils/getTransformSource.js
> +  if ((/(Note|Subtitle|Promo)/g).test(kind)) {
А Promo разве не удалили?

2021-05-19 07:26 UTC, ArtyomResh commented on components/Post/Body/ThematicGap/ThematicGap.jsx
> +const VerticalGap = ({ className }) => {
Я думаю это название лучше подходит компоненту, оно более абстрактное. Давай сам файл компонента тогда так же назовём

2021-05-19 07:26 UTC, ArtyomResh commented on pages/_app.js
> +import '../public/prism-themes/prism-material-light.css'
Я думаю этот импорт мы можем перенести в файл самих страниц

2021-05-19 07:26 UTC, ArtyomResh commented on stories/ThematicGap.stories.mdx
> +Тематический разрыв `<hr>`
Напиши тут ещё, что он представляет из себя дополнительный отступ в 30 и 25 пикселей на десктопе и мобилке соотвественно

2021-05-19 11:39 UTC, vkosinov commented on pages/_app.js
> +import '../public/prism-themes/prism-material-light.css'
```
Global CSS cannot be imported from files other than your Custom <App>. Please move all global CSS imports to pages/_app.js. Or convert the import to Component-Level CSS (CSS Modules).
Read more: https://nextjs.org/docs/messages/css-global
```

выскакивает ошибка

2021-05-20 09:15 UTC, ArtyomResh approved these changes

2021-05-20 09:16 UTC, ArtyomResh commented
@vkosinov Только конфликты теперь поправь :)

2021-05-24 07:30 UTC, ArtyomResh approved these changes

2021-06-04 07:29 UTC, merged