feat: COM-3653 Refactoring a news body components
CSSSR/csssr.blog pull request #625
Opened 2021-06-08 16:00 UTC by vkosinov

## Checklist
- [ ] `data-testid` attribute has been set for new components and interactive blocks according to [documentation](https://github.com/CSSSR/e2e-tools/blob/master/docs/DATA_TESTID.md) 
- [ ] PR is directed to the release branch (if there is a release branch, otherwise this item can be removed)
- [x] Code meets requirements not only from the description of the task, but also from its comments
- [x] Code works correctly on all resolutions
- [x] Task completed with comments for testing (if necessary, otherwise this item can be removed)
- [x] Browser dev tools has no errors
- [x] Got acquainted with the project documentation and updated it if necessary

2021-06-11 12:58 UTC, maksim-kononov-csssr commented
Объясни пожалуйста логику с удалением изображений

2021-06-15 11:04 UTC, ArtyomResh requested changes

2021-06-15 11:04 UTC, ArtyomResh commented on components/Post/Body/ParagraphWithImage/ParagraphWithImage.jsx
> +      )}
Я думаю тут переусложенено. Давай просто все изображения для компонента `ParagraphWithImage` переложим в `public/components/paragraphWithImage/...` и в доке напишем что добавлять изображения для этого компонента нужно так-то сяк-то. Тогда у нас будет один пропс `imageName` и мы избавимся от лишних условий.

2021-06-15 11:04 UTC, ArtyomResh commented on stories/ParagraphWithImage.stories.mdx
> +Название изображения в папке, где лежат изображения для статьи.
На будущее, тут следовало не только указать что каждый пропс делает и значит, но и рассказать когда следует использовать один или другой. Пользователя неочевидно и он может и imageName и postImageName одновременно указать

2021-06-16 13:43 UTC, ArtyomResh requested changes

2021-06-16 14:36 UTC, ArtyomResh approved these changes

2021-06-18 07:25 UTC, merged