feat: COM-3648 Add component SelectedPosts
CSSSR/csssr.blog pull request #632
Opened 2021-06-11 14:51 UTC by vkosinov

## Checklist
- [x] `data-testid` attribute has been set for new components and interactive blocks according to [documentation](https://github.com/CSSSR/e2e-tools/blob/master/docs/DATA_TESTID.md) 
- [x] PR is directed to the release branch (if there is a release branch, otherwise this item can be removed)
- [x] Code meets requirements not only from the description of the task, but also from its comments
- [x] Code works correctly on all resolutions
- [x] Task completed with comments for testing (if necessary, otherwise this item can be removed)
- [x] Browser dev tools has no errors
- [x] Got acquainted with the project documentation and updated it if necessary

2021-06-15 11:24 UTC, maksim-kononov-csssr commented on components/main/SelectedPosts/SelectedPosts.jsx
> +  const slidesCount = posts.length
Я бы назвал переменную slidesAmount. Amount - более стандартное название для количества чего-либо

2021-06-15 11:24 UTC, maksim-kononov-csssr commented on components/main/SelectedPosts/SelectedPosts.jsx
> +  const [clientXStart, setClientXStart] = useState(0)
Значения direction и clientXStart можно не хранить в стейте

2021-06-15 11:24 UTC, maksim-kononov-csssr commented on components/main/SelectedPosts/SelectedPosts.jsx
> +      if (prevActiveIndex === 0 && index < 0) {
При каких обстоятельствах index < 0 и prevActiveIndex !== 0?

2021-06-15 11:24 UTC, maksim-kononov-csssr commented on components/main/SelectedPosts/SelectedPosts.jsx
> +              slideIndex={index}
В компоненте slideIndex и activeIndex используются только для определения "активный ли данный слайд или нет", проще передавать в компонент только одно значение isActive, а вычислять его тут: isActive={slideIndex === activeIndex}

2021-06-15 11:24 UTC, maksim-kononov-csssr commented on components/main/SelectedPosts/SelectedPosts.jsx
> +  ),
Круто что везде описываешь подробный propsTypes

2021-06-15 11:24 UTC, maksim-kononov-csssr commented on components/main/SelectedPosts/Dots/Dots.jsx
> +      {[...Array(slidesCount)].map((_item, index) => (
[...Array(10).keys()]
//=> [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

Так можно будет использовать первый параметр функции map

2021-06-15 12:52 UTC, ArtyomResh approved these changes

2021-06-15 12:52 UTC, ArtyomResh commented on pages/[language]/index.js
> +
Вы неси повторяющийся код из `[language]/[category]/[page].js` и ` pages/[language]/[category]/index.js` и переиспользуй его

2021-06-15 12:52 UTC, ArtyomResh commented on public/icons/arrow-right.svg
> +</svg>
Переложи в `public/components/selectedPosts/`

2021-06-15 12:52 UTC, ArtyomResh commented on selectedPostsEn.json
> +]
Давай сделаем один файл и для ru и для en, будет хешмапа по языкам с массивами под каждый из них. Так будет проще и не придётся в файлах страниц делать дополнительные хешмапы `selectedPostsByLanguage`

2021-06-15 12:52 UTC, ArtyomResh commented on package.json
> +    "react-transition-group": "^4.4.2",
У нас уже есть на проекте библиотека для анимаций – `react-reveal`. Давай её и постараемся использовать. Две библиотеки для одного и того же нам точно не нужны

2021-06-15 12:52 UTC, ArtyomResh commented on components/main/SelectedPosts/Slide/Slide.jsx
> +                  <object>
Я знаю этот хак, он работает, но всё же это хак, давай попробуем сделать на хаковым путём – https://www.sarasoueidan.com/blog/nested-links/

2021-06-15 12:52 UTC, ArtyomResh commented on components/main/SelectedPosts/Slide/Slide.jsx
> +            <MainGrid as="span" className="slide-wrap">
У тебя поверх этого MainGrid есть ещё один в `components/main/SelectedPosts/SelectedPosts.jsx`. Они оба нужны? Нельзя от одного из них отказаться?

2021-06-15 12:52 UTC, ArtyomResh commented on components/main/SelectedPosts/SelectedPosts.jsx
> +  }
Тут, наверное, стоит добавить блок вертикального скролла, пока не произойдёт `handleTouchEnd`, это нативное поведение во многих приложениях на телефоне

2021-06-15 12:53 UTC, ArtyomResh requested changes
Я случайно аппрувнул

2021-06-15 12:59 UTC, vkosinov commented on components/main/SelectedPosts/SelectedPosts.jsx
> +      if (prevActiveIndex === 0 && index < 0) {
Если активный первый слайдер перелистывается не вперед а назад

2021-06-15 13:59 UTC, vkosinov commented on public/icons/arrow-right.svg
> +</svg>
Переложил в папку `public/components/arrows` так как его использует компонент  `Arrows`

2021-06-15 14:09 UTC, vkosinov commented on components/main/SelectedPosts/Slide/Slide.jsx
> +            <MainGrid as="span" className="slide-wrap">
По нему располагаются элементы управления (стрелки и точки).  Внутренний внутри каждого отдельного слайда по нему размещаются внутренние блоки слайда

2021-06-15 14:47 UTC, vkosinov commented on package.json
> +    "react-transition-group": "^4.4.2",
У `react-reveal` [рейтинг хуже ](https://npms.io/search?q=react-reveal) чем у [react-transition-group](https://npms.io/search?q=react-transition-group) и так тонко настроить эффетк  перелистования не получится проще переписать место использования   `react-reveal`

2021-06-15 15:09 UTC, vkosinov commented on components/main/SelectedPosts/SelectedPosts.jsx
> +  }
Так-как у нас рендерится только 1 активный слайд то по сути у нас там не чего скролить так как он помещается на экран

2021-06-15 15:31 UTC, ArtyomResh commented on components/main/SelectedPosts/SelectedPosts.jsx
> +  }
Не, ты не понял, скроллится вся страница, пока я пытаюсь заскролить горизонтально слайд, потому что сложно провести палец чисто горизонтально и это не удобно, я думаю так не должно происходить

2021-06-15 15:47 UTC, ArtyomResh requested changes

2021-06-15 15:47 UTC, ArtyomResh commented on package.json
> +    "react-transition-group": "^4.4.2",
Рейтинг хуже, да, но этот рейтинг получается из нескольких оценок и надо смотреть почему именно он хуже. В данном случае он хуже потому что библиотека менее популярна и давно не обновлялась, по качеству она не уступает, но весит почти в полтора раза легче react-transition-group. Мы сейчас упарываемся по оптимизациям и две либы для одного и того же позволит себе точно не можем. Поэтому я всё же хотел бы оставить одну библиотеку и хотел бы что бы это был `react-reveal`, потому что он легче, тришейкается и API у него проще, а то что он менее популярен и давно не обновлялся в данном случае я думаю что это ок, потому что у нас не еджкейс и простого `Fade` нам хватит.  

Ты уже пробовал настроить на `react-reveal` в чём там была проблема с анимациями?

Как вариант можно поискать какую-нибудь ещё либу, суперлегкую, которая будет делать только одну вещь и переписать на неё. Попробуй в csssroverflow спросить.

2021-06-16 06:01 UTC, vkosinov commented on components/main/SelectedPosts/SelectedPosts.jsx
> +  }
Кажется я тебя понял, но тогда человек не сможет вниз проскролить по моему

2021-06-16 07:24 UTC, ArtyomResh commented on components/main/SelectedPosts/SelectedPosts.jsx
> +  }
Сможет, если на handleTouchStart отключат скролл, а на handleTouchEnd включать скролл

2021-06-16 11:47 UTC, maksim-kononov-csssr approved these changes

2021-06-16 11:48 UTC, merged