Use Img component for Stonehenge image to enable compression
CSSSR/csssr.blog pull request #667
Opened 2021-08-06 17:45 UTC by Nitive

Image size reduction 591 kB → 188 kB in modern browsers (webp compression)

2021-08-06 18:07 UTC, Nitive commented
Также включил оптимизацию для остальных картинок:

59 kB  → 16 kB
227 kB → 35 kB

Это без потери качества, только конвертация в webp

2021-08-09 06:23 UTC, daynin approved these changes

2021-08-09 07:31 UTC, ArtyomResh requested changes

2021-08-09 07:31 UTC, ArtyomResh commented on _posts/en/problems-with-documentation-writing.md
> +[<Img imageName='tweet-about-documentation' alt='A tweet about documentation' />](https://twitter.com/mit_csail/status/1405559612326105090?s=28)
Прикольно, не знал что так можно! Давай только здесь всё же оставим как было, а то почему с этой записью снова появляться [баг с ховером](http://s.csssr.ru/U31J879TR/2021-08-09-10-31-01-2xokw.mp4). Я пока не могу им заняться.

2021-08-09 08:42 UTC, Nitive commented on _posts/en/problems-with-documentation-writing.md
> +[<Img imageName='tweet-about-documentation' alt='A tweet about documentation' />](https://twitter.com/mit_csail/status/1405559612326105090?s=28)
@ArtyomResh не детектился компонент Img в children, [пофиксил](https://github.com/CSSSR/csssr.blog/pull/667/commits/fdcb81e6b5e19695498cf84ac7dcd1eecfcc168b)

2021-08-09 09:10 UTC, ArtyomResh approved these changes

2021-08-09 09:10 UTC, merged