Новая статья в раздел "Культура" (RU)
CSSSR/csssr.blog pull request #673
Opened 2021-09-01 09:53 UTC by romansitnikov

2021-09-06 09:53 UTC, ArtyomResh requested changes
- удали .DS_Store файлы из папок с изображениями `public/images/dont-resize/ru/remote-work-tbilisi/`
- файлу статьи добавь расширение `md`, из-за этого у тебя стенд не собирается, потому что сборщик ищет файл `remote-work-tbilisi.md` и не находит его, потому что ты положил вместо него `remote-work-tbilisi`

2021-09-06 09:53 UTC, ArtyomResh commented on _posts/ru/remote-work-tbilisi
> +Вино, шашлык и хачапури.
Тут если ты хотел сделать структуру заголовок + текст, то лучше заменить выделение жирным `** **` на заголовок третьего уроня `###`, потому что выделение жирным [не даёт переноса на следующую строку](http://s.csssr.ru/U31J879TR/2021-09-06-12-47-48-cypdw_.png), а так же в первом абзаце выделение жирным [ведёт себя по другому](http://s.csssr.ru/U31J879TR/2021-09-06-12-49-23-k79ks_.png) ([им выделяют символы для красной строки](http://s.csssr.ru/U31J879TR/2021-09-06-12-51-45-ihbwg_.png))

2021-09-06 09:53 UTC, ArtyomResh commented on _posts/ru/remote-work-tbilisi
> +<Img imageName='tbilisi' alt='Вид на Тбилиси из горной деревни Целовани'>
За нормальный alt респект 👍

2021-11-08 08:16 UTC, closed without merging

2021-11-08 08:16 UTC, vkosinov commented
https://github.com/CSSSR/csssr.blog/pull/684 - дубль