COM-3551: Add markdown lint
CSSSR/csssr.blog pull request #695
Opened 2021-11-08 13:44 UTC by vkosinov

COM-3551

## Checklist
- [ ] `data-testid` attribute has been set for new components and interactive blocks according to [documentation](https://github.com/CSSSR/e2e-tools/blob/master/docs/DATA_TESTID.md) 
- [x] PR is directed to the release branch (if there is a release branch, otherwise this item can be removed)
- [x] Code meets requirements not only from the description of the task, but also from its comments
- [x] Code works correctly on all resolutions
- [x] Task completed with comments for testing (if necessary, otherwise this item can be removed)
- [x] Browser dev tools has no errors
- [ ] Got acquainted with the project documentation and updated it if necessary

## Optional (if you have something to add, otherwise this heading and the paragraph below can be removed)
https://github.com/DavidAnson/markdownlint
https://github.com/igorshubovych/markdownlint-cli

2021-11-12 07:56 UTC, ArtyomResh requested changes

2021-11-12 07:56 UTC, ArtyomResh commented on _posts/ru/lint-your-css.md
> + background-image url(../images/background.png)
Кажется, вот тут странные отступы линтер сделал

2021-11-12 07:56 UTC, ArtyomResh commented on _posts/ru/ng-options.md
> + <select ng-model="request.volary" ng-change="setDefaultCage()" ng-options="volary.text for volary in volaries track by volary.volary_id" class="form-control"></select>
Мне кажется тут лучше настроить двойной пробел или два таба

2021-11-12 07:56 UTC, ArtyomResh commented on _posts/ru/semantics-in-programming.md
> +;<Component />
Кажется линтер лишнего добавил

2021-11-12 07:56 UTC, ArtyomResh commented on _posts/ru/side-effects.md
> +  > -- Братья Стругацкие
Тут линтер тоже лишнего порезал

2021-11-12 07:56 UTC, ArtyomResh commented on _posts/ru/side-effects.md
> +> -- Гераклит
тут тоже линтер перестарался)

2021-11-12 07:56 UTC, ArtyomResh commented on _posts/ru/side-effects.md
> +> -- [Саймон Пейтон Джонс](http://fprog.ru/2010/issue6/interview-simon-peyton-jones/)
И тут

2021-11-17 15:33 UTC, ArtyomResh approved these changes

2024-10-03 07:54 UTC, vkosinov commented
The expiration date has passed

2024-10-03 07:54 UTC, closed without merging